{
  "hash": "e847a141e6e60b89b3a09f5695fff2cd",
  "result": {
    "markdown": "---\ntitle: \"Advent of Code 2021: Days 6-10\"\ndescription: |\n  My solutions to the #AdventOfCode2021 coding challenges, days 6 through 10.\ndate: 2021-12-06\nparams:\n  date: 2021-12-06\n  slug: \"advent-of-code-2021-days-6-10\"\ncategories:\n  - Advent of Code\n  - Python\n  - R\nengine: knitr\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R setup\"}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(gt)\nlibrary(lubridate)\n```\n:::\n\n\n<details><summary>Python setup</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(reticulate)\nuse_virtualenv(\"r-reticulate\")\n```\n:::\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\n```\n:::\n\n\n</details>\n\n## Day 6: Lanternfish\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday6 <- read_lines(\"day06-input.txt\")\nstr_trunc(day6, 70)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"5,1,4,1,5,1,1,5,4,4,4,4,5,1,2,2,1,3,4,1,1,5,1,5,2,2,2,2,1,4,2,4,3,3...\"\n```\n:::\n:::\n\n\n### Part 1\n\n>A massive school of glowing lanternfish swims past. They must spawn quickly to reach such large numbers - maybe exponentially quickly? You should model their growth rate to be sure.\nAlthough you know nothing about this specific species of lanternfish, you make some guesses about their attributes. Surely, each lanternfish creates a new lanternfish once every 7 days.\nHowever, this process isn't necessarily synchronized between every lanternfish - one lanternfish might have 2 days left until it creates another lanternfish, while another might have 4. So, you can model each fish as a single number that represents the number of days until it creates a new lanternfish.\nFurthermore, you reason, a new lanternfish would surely need slightly longer before it's capable of producing more lanternfish: two more days for its first cycle.\n\n>Each day, a 0 becomes a 6 and adds a new 8 to the end of the list, while each other number decreases by 1 if it was present at the start of the day.\nFind a way to simulate lanternfish. How many lanternfish would there be after 80 days?\n\nThis is simple enough to do with a vector and a loop over 80 days:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfish_timers <- strsplit(day6, \",\") %>% unlist() %>% as.numeric()\n\nfor (day in seq(1:80)) {\n  # Decrease each timer by one\n  fish_timers <- map_dbl(fish_timers, ~{.x - 1})\n  \n  # Look for elapsed timers\n  elapsed_timers <- fish_timers < 0\n  # Reset them to 6\n  fish_timers[elapsed_timers] <- 6\n  # Add new fish with timers starting at 8\n  fish_timers <- c(fish_timers, rep(8, sum(elapsed_timers)))\n}\n\n# Count the number of fish after 80 days\nlength(fish_timers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 355386\n```\n:::\n:::\n\n\nFor Python, I'll use a list:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfish_timers = [int(x) for x in r.day6.split(',')]\n\nfor day in range(80):\n  fish_timers = [f - 1 for f in fish_timers]\n  \n  n_new_fish = fish_timers.count(-1)\n  fish_timers = [6 if f == -1 else f for f in fish_timers]\n  \n  if n_new_fish > 0:\n    fish_timers.extend([8] * n_new_fish)\n\nlen(fish_timers) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n355386\n```\n:::\n:::\n\n\n### Part 2\n\n>Suppose the lanternfish live forever and have unlimited food and space. Would they take over the entire ocean?\nHow many lanternfish would there be after 256 days?\n\nFor this part, the list of fish would quickly become too large to store in memory after 256 days.\nInstead, find the number of fish at each timer value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfish_timers_df <- tibble(\n  timer = strsplit(day6, \",\") %>% unlist() %>% as.numeric()\n) %>%\n  count(timer, name = \"n_fish\") %>%\n  # Need to fill in the missing days with 0 fish\n  bind_rows(tibble(timer = c(0, 6, 7, 8), n_fish = c(0, 0, 0, 0))) %>%\n  arrange(timer)\nfish_timers_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 9 × 2\n  timer n_fish\n  <dbl>  <dbl>\n1     0      0\n2     1     96\n3     2     54\n4     3     48\n5     4     51\n6     5     51\n7     6      0\n8     7      0\n9     8      0\n```\n:::\n:::\n\n\nNow it is a matter of looping through the days and updating the counts:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (day in 1:256) {\n  # Decrease the timer values by 1\n  fish_timers_df <- fish_timers_df %>% mutate(timer = timer - 1)\n  # Count new fish\n  new_fish <- fish_timers_df$n_fish[fish_timers_df$timer == -1]\n  \n  # Add new fish with timers at 8 \n  fish_timers_df <- fish_timers_df %>%\n    bind_rows(tibble(timer = 8, n_fish = new_fish))\n \n  # Reset elapsed timers to 6\n  fish_timers_df$n_fish[fish_timers_df$timer == 6] <-\n    fish_timers_df$n_fish[fish_timers_df$timer == 6] +\n    new_fish\n  \n  # Remove the -1 values now that they've been accounted for\n  fish_timers_df <- fish_timers_df %>% filter(timer != -1)\n}\n\nfish_timers_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 9 × 2\n  timer       n_fish\n  <dbl>        <dbl>\n1     0 141979186737\n2     1 163480438824\n3     2 172999320549\n4     3 189419502198\n5     4 211569179655\n6     5 220260612873\n7     6 255636828738\n8     7 118721109675\n9     8 139349146560\n```\n:::\n:::\n\n\nThat's a lot of fish.\nTo get the answer, I need to `format` the sum so that it is not printed in scientific notation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat(sum(fish_timers_df$n_fish), scientific = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"1613415325809\"\n```\n:::\n:::\n\n\nPython:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfish_timers_df = pd.DataFrame({'timer': [int(x) for x in r.day6.split(',')]})\nfish_timers_df = fish_timers_df.value_counts('timer') \\\n  .rename_axis('n_fish') \\\n  .reindex(range(9), fill_value = 0)\n  \nfor day in range(256):\n  n_new_fish = fish_timers_df[0]\n  \n  for i in range(1, len(fish_timers_df)):\n    fish_timers_df[i-1] = fish_timers_df[i]\n  \n  fish_timers_df[6] += n_new_fish\n  fish_timers_df[8] = n_new_fish\n  \nfish_timers_df.sum()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1613415325809\n```\n:::\n:::\n\n\n## Day 7: The Treachery of Whales\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday7 <- read_lines(\"day07-input.txt\")\nstr_trunc(day7, 70)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,10...\"\n```\n:::\n:::\n\n\n### Part 1\n\n>A giant whale has decided your submarine is its next meal, and it's much faster than you are. There's nowhere to run!\n>\nSuddenly, a swarm of crabs (each in its own tiny submarine - it's too deep for them otherwise) zooms in to rescue you! They seem to be preparing to blast a hole in the ocean floor; sensors indicate a massive underground cave system just beyond where they're aiming!\n>\nThe crab submarines all need to be aligned before they'll have enough power to blast a large enough hole for your submarine to get through. However, it doesn't look like they'll be aligned before the whale catches you! Maybe you can help?\n>\nThere's one major catch - crab submarines can only move horizontally.\n>\nYou quickly make a list of the horizontal position of each crab (your puzzle input). Crab submarines have limited fuel, so you need to find a way to make all of their horizontal positions match while requiring them to spend as little fuel as possible.\n>\nEach change of 1 step in horizontal position of a single crab costs 1 fuel. \nDetermine the horizontal position that the crabs can align to using the least fuel possible. How much fuel must they spend to align to that position?\n\nThe amount of fuel spent by a crab $i$ at position $x_i$ moving to position $x_0$ can be represented as the absolute deviation $|x_i - x_0|$.\nWe seek the position $x_0$ that minimizes the sum of absolute deviations for all $N$ crabs:\n\n\n$$\n\\sum_i^N |x_i - x_0|\n$$\n\n\nMy mathematical proof skills are rusty (it has been about 8 years since I took Mathematical Reasoning at UPEI), but Google tells me that [the median minimizes the sum of absolute deviations](https://math.stackexchange.com/questions/113270/the-median-minimizes-the-sum-of-absolute-deviations-the-ell-1-norm).\nThe median position of the input is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrab_positions <- strsplit(day7, \",\") %>% unlist() %>% as.numeric()\nmedian(crab_positions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 331\n```\n:::\n:::\n\n\nAnd so the total fuel taken for each crab to move to this position is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(abs(crab_positions - median(crab_positions)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 349769\n```\n:::\n:::\n\n\nPython:\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncrab_positions = [int(x) for x in r.day7.split(',')]\nsum([np.abs(x - np.median(crab_positions)) for x in crab_positions])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n349769.0\n```\n:::\n:::\n\n\n### Part 2\n\n>\nThe crabs don't seem interested in your proposed solution. Perhaps you misunderstand crab engineering?\n>\nAs it turns out, crab submarine engines don't burn fuel at a constant rate. Instead, each change of 1 step in horizontal position costs 1 more unit of fuel than the last: the first step costs 1, the second step costs 2, the third step costs 3, and so on.\n>\nDetermine the horizontal position that the crabs can align to using the least fuel possible so they can make you an escape route! How much fuel must they spend to align to that position?\n\nMy first thought for calculating this fuel was the cumulative sum.\nFor example, moving 7 steps would cost fuel equal to the last value of this `cumsum()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncumsum(1:7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  1  3  6 10 15 21 28\n```\n:::\n:::\n\n\nBut then I figured there is probably a useful formula for this sum, and another lazy Google search tells me that these are called [triangular numbers](https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_%E2%8B%AF) with the simple formula:\n\n\n$$\n\\sum_{i=1}^n k = \\frac{n (n + 1)}{2}.\n$$\n\n\nAnd so we want to find $x_0$ that minimizes:\n\n\n$$\n\\sum_i^N \\frac{|x_i - x_0|(|x_i - x_0| + 1)}{2}.\n$$\n\n\nI'm not aware of a simple solution (like the median in part 1) to this optimization problem.\nThe brute force way is to loop over values of $x_0$, ranging from $\\text{min}(x_i)$ to $\\text{max}(x_i)$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfuel_spent <- tibble(\n  x0 = seq(min(crab_positions), max(crab_positions))\n) %>%\n  mutate(\n    crab_dist = map(x0, ~abs(crab_positions - .x)),\n    fuel_spent = map_dbl(crab_dist, ~sum(.x * (.x + 1) / 2))\n  ) %>%\n  arrange(fuel_spent)\nhead(fuel_spent)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n     x0 crab_dist     fuel_spent\n  <int> <list>             <dbl>\n1   479 <dbl [1,000]>   99540554\n2   480 <dbl [1,000]>   99540639\n3   478 <dbl [1,000]>   99541469\n4   481 <dbl [1,000]>   99541724\n5   477 <dbl [1,000]>   99543385\n6   482 <dbl [1,000]>   99543809\n```\n:::\n:::\n\n\nWe find that $x_0$ = 479 minimizes the fuel with 99540554 spent.\n\nUse a `pandas.Series` to do the same:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfuel_spent = pd.Series(dtype = np.float64)\nfor x0 in range(min(crab_positions), max(crab_positions)):\n  crab_dist = [np.abs(x - x0) for x in crab_positions]\n  fuel_spent.at[x0] = sum([d * (d + 1) / 2 for d in crab_dist])\n  \nfuel_spent.sort_values().head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n479    99540554.0\n480    99540639.0\n478    99541469.0\n481    99541724.0\n477    99543385.0\ndtype: float64\n```\n:::\n:::\n\n\n## Day 8: Seven Segment Search\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday8 <- read_lines(\"day08-input.txt\")\nhead(day8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"cbgefad agc fdega cgdf ecdgfa efgca gaefbd edagbc cg ecafb | cdgafbe cfdg cg gac\"   \n[2] \"gcbdfe cgefb bgadcfe de cfabeg cbgade dbfe ced acfdg egdcf | de bedf ecdgf ecd\"     \n[3] \"dcafgb eagdfb bagdefc abg ba afbc bdgec cdgab gaedfc gadfc | abg ba agfdc gab\"      \n[4] \"agfbe fc fgbadec bdgcef gcdbe fbcead ebgcf cfe gdfc dcbega | edfabc efgab cdfg ecf\" \n[5] \"fcdeg cfbedg dcfeba fge fcdga ebdg cfebd edgcabf efbagc ge | cbdgef begcaf ge dbcfe\"\n[6] \"fceadbg ecbg cab cb bdfcea agfce cfaedg gadbf bfagc gceabf | cba cab bc bgce\"       \n```\n:::\n:::\n\n\n### Part 1\n\n>You barely reach the safety of the cave when the whale smashes into the cave mouth, collapsing it. Sensors indicate another exit to this cave at a much greater depth, so you have no choice but to press on.\n>\nAs your submarine slowly makes its way through the cave system, you notice that the four-digit seven-segment displays in your submarine are malfunctioning; they must have been damaged during the escape. You'll be in a lot of trouble without them, so you'd better figure out what's wrong.\n>\nEach digit of a seven-segment display is rendered by turning on or off any of seven segments named `a` through `g`:\n\n```\n  0:      1:      2:      3:      4:     5:      6:      7:      8:      9:\n aaaa    ....    aaaa    aaaa    ....   aaaa    aaaa    aaaa    aaaa    aaaa\nb    c  .    c  .    c  .    c  b    c b    .  b    .  .    c  b    c  b    c\nb    c  .    c  .    c  .    c  b    c b    .  b    .  .    c  b    c  b    c\n ....    ....    dddd    dddd    dddd  dddd    dddd    ....    dddd    dddd\ne    f  .    f  e    .  .    f  .    f .    f  e    f  .    f  e    f  .    f  \ne    f  .    f  e    .  .    f  .    f .    f  e    f  .    f  e    f  .    f\n gggg    ....    gggg    gggg    ....   gggg    gggg    ....    gggg    gggg\n```\n>\nSo, to render a `1`, only segments `c` and `f` would be turned on; the rest would be off. To render a `7`, only segments `a`, `c`, and `f` would be turned on.\n>\nThe problem is that the signals which control the segments have been mixed up on each display. The submarine is still trying to display numbers by producing output on signal wires `a` through `g`, but those wires are connected to segments randomly. Worse, the wire/segment connections are mixed up separately for each four-digit display! (All of the digits within a display use the same connections, though.)\n>\nFor each display, you watch the changing signals for a while, make a note of all ten unique signal patterns you see, and then write down a single four digit output value (your puzzle input). Using the signal patterns, you should be able to work out which pattern corresponds to which digit.\n>\nEach entry consists of ten unique signal patterns, a `|` delimiter, and finally the four digit output value. Within an entry, the same wire/segment connections are used (but you don't know what the connections actually are). The unique signal patterns correspond to the ten different ways the submarine tries to render a digit using the current wire/segment connections.\n>\nIn the output values, how many times do digits 1, 4, 7, or 8 appear?\n\nFirst, for my own reference, compile the number of segments used by each digit:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndigit_segments_count <- tribble(\n  ~digit, ~n_segments,\n  0, 6,\n  1, 2,\n  2, 5,\n  3, 5,\n  4, 4,\n  5, 5,\n  6, 6,\n  7, 3,\n  8, 7,\n  9, 6\n)\ndigit_segments_count %>%\n  group_by(n_segments) %>%\n  summarise(digits = str_c(digit, collapse = \",\"), .groups = \"drop\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  n_segments digits\n       <dbl> <chr> \n1          2 1     \n2          3 7     \n3          4 4     \n4          5 2,3,5 \n5          6 0,6,9 \n6          7 8     \n```\n:::\n:::\n\n\nI see why part 1 is asking about just the digits 1, 4, 7, and 8 -- they consist of a unique number of segments (2, 4, 3, and 7, respectively).\n\nSplit the input into the the signal patterns (ten unique values) and four digit output values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday8_split <- strsplit(day8, \" \\\\| \") %>%\n  map(strsplit, \" \")\n\nday8_df <-\n  tibble(\n    signal_patterns = map(day8_split, 1),\n    output = map(day8_split, 2)\n  )\nday8_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 200 × 2\n   signal_patterns output   \n   <list>          <list>   \n 1 <chr [10]>      <chr [4]>\n 2 <chr [10]>      <chr [4]>\n 3 <chr [10]>      <chr [4]>\n 4 <chr [10]>      <chr [4]>\n 5 <chr [10]>      <chr [4]>\n 6 <chr [10]>      <chr [4]>\n 7 <chr [10]>      <chr [4]>\n 8 <chr [10]>      <chr [4]>\n 9 <chr [10]>      <chr [4]>\n10 <chr [10]>      <chr [4]>\n# … with 190 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nConsider a single row of this data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignals1 <- day8_df %>% slice(2) %>%\n  unnest(signal_patterns) %>% pull(signal_patterns)\noutput1 <- day8_df %>% slice(2) %>% unnest(output) %>% pull(output)\nsignals1; output1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"gcbdfe\"  \"cgefb\"   \"bgadcfe\" \"de\"      \"cfabeg\"  \"cbgade\"  \"dbfe\"   \n [8] \"ced\"     \"acfdg\"   \"egdcf\"  \n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"de\"    \"bedf\"  \"ecdgf\" \"ecd\"  \n```\n:::\n:::\n\n\nWe actually don't need the 10 `signal_patterns` for part 1 -- we just need to find the string length of the `output` values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnchar(output1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2 4 5 3\n```\n:::\n:::\n\n\nFrom these lengths, I know that the first digit is 1, the second digit is 4, the third digit is one of {2, 3, 5}, and the fourth digit is 7.\nWe want to count the occurrences of 1, 4, 7 and 8, so this row contributes 3 to that count.\nApply this logic to the full input:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npart1_count <- day8_df %>%\n  mutate(\n    n_1_4_7_8 = map_int(\n      output,\n      ~sum(nchar(.x) %in% c(2, 3, 4, 7))\n    )\n  )\npart1_count\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 200 × 3\n   signal_patterns output    n_1_4_7_8\n   <list>          <list>        <int>\n 1 <chr [10]>      <chr [4]>         4\n 2 <chr [10]>      <chr [4]>         3\n 3 <chr [10]>      <chr [4]>         3\n 4 <chr [10]>      <chr [4]>         2\n 5 <chr [10]>      <chr [4]>         1\n 6 <chr [10]>      <chr [4]>         4\n 7 <chr [10]>      <chr [4]>         3\n 8 <chr [10]>      <chr [4]>         2\n 9 <chr [10]>      <chr [4]>         2\n10 <chr [10]>      <chr [4]>         4\n# … with 190 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\nsum(part1_count$n_1_4_7_8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 514\n```\n:::\n:::\n\n\n### Part 2\n\n>\nFor each entry, determine all of the wire/segment connections and decode the four-digit output values. What do you get if you add up all of the output values?\n\nConsider again the segment patterns for each digit:\n\n```\n  0:      1:      2:      3:      4:     5:      6:      7:      8:      9:\n aaaa    ....    aaaa    aaaa    ....   aaaa    aaaa    aaaa    aaaa    aaaa\nb    c  .    c  .    c  .    c  b    c b    .  b    .  .    c  b    c  b    c\nb    c  .    c  .    c  .    c  b    c b    .  b    .  .    c  b    c  b    c\n ....    ....    dddd    dddd    dddd  dddd    dddd    ....    dddd    dddd\ne    f  .    f  e    .  .    f  .    f .    f  e    f  .    f  e    f  .    f  \ne    f  .    f  e    .  .    f  .    f .    f  e    f  .    f  e    f  .    f\n gggg    ....    gggg    gggg    ....   gggg    gggg    ....    gggg    gggg\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndigit_segments <- c(\"abcefg\", \"cf\", \"acdeg\", \"acdfg\", \"bcdf\",\n                    \"abdfg\", \"abdefg\", \"acf\", \"abcdefg\", \"abcdfg\")\n```\n:::\n\n\nWe know digits 1, 4, 7 and 8 are uniquely identified by their number of segments.\nWe also know that the digit 1 has two overlapping segments (`c` and `f`) with the digit 0.\nThis can be derived with `intersect` on the letters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompute_overlap <- function(segments1, segments2) {\n  length(\n    intersect(strsplit(segments1, \"\") %>% unlist(),\n              strsplit(segments2, \"\") %>% unlist())\n  )\n}\ncompute_overlap(digit_segments[1], digit_segments[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2\n```\n:::\n:::\n\n\nCompute the amount of overlap between each pair of digits:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndigit_overlap <- \n  crossing(\n    tibble(digit1 = 0:9, segments1 = digit_segments),\n    tibble(digit2 = 0:9, segments2 = digit_segments)\n  ) %>%\n  filter(digit1 != digit2) %>%\n  mutate(\n    n_segment_overlap = map2_int(\n      segments1, segments2,\n      compute_overlap\n    )\n  )\ndigit_overlap %>%\n  select(digit1, digit2, n_segment_overlap) %>%\n  pivot_wider(names_from = digit2, values_from = n_segment_overlap) %>%\n  relocate(`0`, .before = `1`) %>% # Need to correct order of columns\n  gt(rowname_col = \"digit1\") %>%\n  sub_missing(everything(), missing_text = \"\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"salthtujtt\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#salthtujtt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#salthtujtt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#salthtujtt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#salthtujtt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#salthtujtt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#salthtujtt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#salthtujtt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#salthtujtt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#salthtujtt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#salthtujtt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#salthtujtt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#salthtujtt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#salthtujtt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#salthtujtt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#salthtujtt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#salthtujtt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#salthtujtt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#salthtujtt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#salthtujtt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#salthtujtt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#salthtujtt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#salthtujtt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#salthtujtt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#salthtujtt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#salthtujtt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#salthtujtt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#salthtujtt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#salthtujtt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#salthtujtt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#salthtujtt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#salthtujtt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#salthtujtt .gt_left {\n  text-align: left;\n}\n\n#salthtujtt .gt_center {\n  text-align: center;\n}\n\n#salthtujtt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#salthtujtt .gt_font_normal {\n  font-weight: normal;\n}\n\n#salthtujtt .gt_font_bold {\n  font-weight: bold;\n}\n\n#salthtujtt .gt_font_italic {\n  font-style: italic;\n}\n\n#salthtujtt .gt_super {\n  font-size: 65%;\n}\n\n#salthtujtt .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#salthtujtt .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#salthtujtt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#salthtujtt .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#salthtujtt .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#salthtujtt .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">0</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">6</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">7</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">8</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">9</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right gt_stub\">0</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_right\">5</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">1</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">2</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">2</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">4</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">3</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">5</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">4</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">4</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">5</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">5</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">6</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_right\">5</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">7</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">3</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">8</td>\n<td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\"></td>\n<td class=\"gt_row gt_right\">6</td></tr>\n    <tr><td class=\"gt_row gt_right gt_stub\">9</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_right\"></td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nUsing these relationships, it is simply a matter of elimination to determine which pattern of segments corresponds to which digit:\n\n* The digit 1 has 2 segments.\n* The digit 4 has 4 segments.\n* The digit 7 has 3 segments.\n* The digit 8 has 7 segments.\n* The digits 2, 3 and 5 have 5 segments.\n    * The digit 3 shares 2 segments with 1.\n    * The digit 2 shares 2 segments with 4.\n    * The digit 5 remains.\n* The digits 0, 6 and 9 have 6 segments.\n    * The digit 6 shares 2 segments with 7.\n    * The digit 9 shares 4 segments with 4.\n    * The digit 0 remains.\n    \nWrite a function that follows this logic, and returns a list mapping segment patterns to digits:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_digit_map <- function(signals) {\n  digit_map <- list()\n  \n  d1 <- signals[nchar(signals) == 2]\n  digit_map[d1] <- 1\n  \n  d4 <- signals[nchar(signals) == 4]\n  digit_map[d4] <- 4\n  \n  d7 <- signals[nchar(signals) == 3]\n  digit_map[d7] <- 7\n  \n  d8 <- signals[nchar(signals) == 7]\n  digit_map[d8] <- 8\n  \n  # Remove the four digits identified so far\n  signals <- setdiff(signals, names(digit_map))\n  \n  d3 <- signals[nchar(signals) == 5 & map_int(signals, compute_overlap, d1) == 2]\n  digit_map[d3] <- 3\n  signals <- setdiff(signals, d3)\n  \n  d2 <- signals[nchar(signals) == 5 & map_int(signals, compute_overlap, d4) == 2]\n  digit_map[d2] <- 2\n  signals <- setdiff(signals, d2)\n  \n  d5 <- signals[nchar(signals) == 5]\n  digit_map[d5] <- 5\n  signals <- setdiff(signals, d5)\n  \n  d6 <- signals[nchar(signals) == 6 & map_int(signals, compute_overlap, d7) == 2]\n  digit_map[d6] <- 6\n  signals <- setdiff(signals, d6)\n  \n  d9 <- signals[nchar(signals) == 6 & map_int(signals, compute_overlap, d4) == 4]\n  digit_map[d9] <- 9\n  signals <- setdiff(signals, d9)\n  \n  # The last digit is 0\n  digit_map[signals] <- 0\n  \n  return(digit_map)\n}\n```\n:::\n\n\nOne last step before applying this function is the sort the segments alphabetically, because the output does not necessarily match the patterns in the signals, e.g. \"bedf\" may appear as \"dbfe\" in the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort_segment <- function(segment) {\n  strsplit(segment, \"\")[[1]] %>%\n    sort() %>%\n    paste0(collapse = \"\")\n}\n\nday8_df <- day8_df %>%\n  mutate(\n    signal_patterns = map(\n      signal_patterns, ~map_chr(.x, sort_segment)\n    ),\n    output = map(\n      output, ~map_chr(.x, sort_segment)\n    )\n  )\nday8_df$signal_patterns[[5]]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"cdefg\"   \"bcdefg\"  \"abcdef\"  \"efg\"     \"acdfg\"   \"bdeg\"    \"bcdef\"  \n [8] \"abcdefg\" \"abcefg\"  \"eg\"     \n```\n:::\n:::\n\n\nNow find the digit mapping for each set of signals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday8_df <- day8_df %>%\n  mutate(digit_map = map(signal_patterns, get_digit_map))\nday8_df$digit_map[[5]] %>% glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 10\n $ eg     : num 1\n $ bdeg   : num 4\n $ efg    : num 7\n $ abcdefg: num 8\n $ cdefg  : num 3\n $ acdfg  : num 2\n $ bcdef  : num 5\n $ abcdef : num 6\n $ bcdefg : num 9\n $ abcefg : num 0\n```\n:::\n:::\n\n\nNow use each `digit_map` to determine the 4 digit output codes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday8_df <- day8_df %>%\n  mutate(\n    output_decoded = map2_int(\n      output, digit_map,\n      ~as.integer(paste0(.y[.x], collapse = \"\"))\n    )\n  )\nday8_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 200 × 4\n   signal_patterns output    digit_map         output_decoded\n   <list>          <list>    <list>                     <int>\n 1 <chr [10]>      <chr [4]> <named list [10]>           8417\n 2 <chr [10]>      <chr [4]> <named list [10]>           1437\n 3 <chr [10]>      <chr [4]> <named list [10]>           7157\n 4 <chr [10]>      <chr [4]> <named list [10]>            247\n 5 <chr [10]>      <chr [4]> <named list [10]>           9015\n 6 <chr [10]>      <chr [4]> <named list [10]>           7714\n 7 <chr [10]>      <chr [4]> <named list [10]>           7764\n 8 <chr [10]>      <chr [4]> <named list [10]>           1425\n 9 <chr [10]>      <chr [4]> <named list [10]>           9677\n10 <chr [10]>      <chr [4]> <named list [10]>           4784\n# … with 190 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nAnd finally, the sum:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(day8_df$output_decoded)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1012272\n```\n:::\n:::\n\n\n## Day 9: Smoke Basin\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday9 <- read_lines(\"day09-input.txt\")\nhead(day9) %>% str_trunc(70)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"4210129998765678999876598999987654567899891099876534567899989543458...\"\n[2] \"4321298987674567998965467898996543478998789987654323478998775412367...\"\n[3] \"5734987794543678987654356987987656567897678998943214589987654323456...\"\n[4] \"7649876543212347898765567896598767678976567899876323678998775454868...\"\n[5] \"8756989652103456999898678966459878989785456989965456789999976565699...\"\n[6] \"9897898773212367895939989656346989799654347778976587997896989876989...\"\n```\n:::\n:::\n\n\n### Part 1\n\n>These caves seem to be lava tubes. Parts are even still volcanically active; small hydrothermal vents release smoke into the caves that slowly settles like rain.\n>\nIf you can model how the smoke flows through the caves, you might be able to avoid it and be that much safer. The submarine generates a heightmap of the floor of the nearby caves for you (your puzzle input).\nSmoke flows to the lowest point of the area it's in.\nEach number corresponds to the height of a particular location, where 9 is the highest and 0 is the lowest a location can be.\n>\nYour first goal is to find the low points - the locations that are lower than any of its adjacent locations. Most locations have four adjacent locations (up, down, left, and right); locations on the edge or corner of the map have three or two adjacent locations, respectively. (Diagonal locations do not count as adjacent.)\n>\nThe risk level of a low point is 1 plus its height.\nFind all of the low points on your heightmap. What is the sum of the risk levels of all low points on your heightmap?\n\nI'll use a base R `matrix` to represent the height map of the cave floor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Split the columns and convert to integers\nheight_map <- day9 %>% map(~unlist(strsplit(.x, \"\")) %>% as.integer)\n# Convert it to a matrix\nheight_map <- matrix(unlist(height_map), nrow = length(height_map), byrow = TRUE)\n\nheight_map[1:10, 1:10]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]\n [1,]    4    2    1    0    1    2    9    9    9     8\n [2,]    4    3    2    1    2    9    8    9    8     7\n [3,]    5    7    3    4    9    8    7    7    9     4\n [4,]    7    6    4    9    8    7    6    5    4     3\n [5,]    8    7    5    6    9    8    9    6    5     2\n [6,]    9    8    9    7    8    9    8    7    7     3\n [7,]    5    9    9    8    9    9    9    7    6     5\n [8,]    4    5    6    9    8    9    9    8    7     5\n [9,]    3    4    5    6    7    8    9    9    7     6\n[10,]    2    3    4    8    9    9    9    9    8     7\n```\n:::\n:::\n\n\nI'll also define a helper function that finds neighboring points (while still within the bounds of the matrix):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_neighbor_coords <- function(row, col, max_row, max_col) {\n  neighbor_coords <- cbind(row + c(-1, 1, 0, 0),\n                           col + c(0, 0, -1, 1))\n  \n  in_bounds <- (neighbor_coords[,1] <= max_row) & (neighbor_coords[,1] > 0) &\n    (neighbor_coords[,2] <= max_col) & (neighbor_coords[,2] > 0)\n  neighbor_coords[in_bounds, , drop = FALSE]\n}\n```\n:::\n\n\nLoop over all points and determine if it is a low point:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlow_point_heights <- c()\nfor (row in 1:nrow(height_map)) {\n  for (col in 1:ncol(height_map)) {\n    height <- height_map[row, col]\n    \n    # Get adjacent points\n    neighbor_coords <- get_neighbor_coords(row, col,\n                                           nrow(height_map), ncol(height_map))\n    neighbor_heights <- height_map[neighbor_coords]\n    \n    # Is it the lowest point?\n    if (all(height < neighbor_heights)) {\n      low_point_heights <- c(low_point_heights, height)\n    } \n  }\n}\nlow_point_heights\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] 0 0 0 0 1 3 1 3 1 0 2 2 2 0 1 1 0 0 2 1 0 2 0 0 0 1 3 0 6 2 2 1 1 0 2 1 1\n [38] 0 3 1 0 3 0 1 1 0 0 0 4 1 5 0 0 3 2 0 0 2 0 3 1 0 2 0 1 2 0 0 0 2 2 1 1 5\n [75] 2 1 0 2 0 1 1 4 1 2 2 1 0 2 1 1 1 0 0 0 2 0 0 2 1 0 0 1 0 4 0 0 0 0 1 5 1\n[112] 4 2 2 0 4 2 2 0 1 0 1 0 0 0 1 1 0 3 3 1 1 3 3 0 1 0 2 1 1 0 0 3 0 0 0 1 0\n[149] 3 2 1 0 0 1 1 0 0 0 0 0 2 0 0 1 0 0 3 1 0 0 1 3 0 1 0 0 0 0 1 0 2 2 1 1 4\n[186] 0 0 3 1 1 6 5 1 0 1 0 0 0\n```\n:::\n:::\n\n\nThen add 1 to get the risk level and sum it up:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(low_point_heights + 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 417\n```\n:::\n:::\n\n\nIn Python, represent the height map with a 2d `numpy.array`:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nheight_map = np.array([[height for height in row] for row in r.day9],\n                      dtype = int)\nheight_map[0:9, 0:9]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\narray([[4, 2, 1, 0, 1, 2, 9, 9, 9],\n       [4, 3, 2, 1, 2, 9, 8, 9, 8],\n       [5, 7, 3, 4, 9, 8, 7, 7, 9],\n       [7, 6, 4, 9, 8, 7, 6, 5, 4],\n       [8, 7, 5, 6, 9, 8, 9, 6, 5],\n       [9, 8, 9, 7, 8, 9, 8, 7, 7],\n       [5, 9, 9, 8, 9, 9, 9, 7, 6],\n       [4, 5, 6, 9, 8, 9, 9, 8, 7],\n       [3, 4, 5, 6, 7, 8, 9, 9, 7]])\n```\n:::\n:::\n\n\nThen apply the same logic to get the sum of risk levels:\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef get_neighbor_coords(row, col, max_row, max_col):\n  neighbor_coords = [[row + d for d in [-1, 1, 0, 0]],\n                     [col + d for d in [0, 0, -1, 1]]]\n  neighbor_coords = np.array(neighbor_coords).T\n  \n  in_bounds = (neighbor_coords[:, 0] >= 0) & \\\n    (neighbor_coords[:, 0] < max_row) & \\\n    (neighbor_coords[:, 1] >= 0) & \\\n    (neighbor_coords[:, 1] < max_col)\n    \n  return(neighbor_coords[in_bounds, :])\n\nlow_point_heights = []\n\nfor row in range(height_map.shape[0]):\n  for col in range(height_map.shape[1]):\n    height = height_map[row, col]\n    \n    neighbor_coords = get_neighbor_coords(row, col,\n                                          height_map.shape[0],\n                                          height_map.shape[1])\n    neighbor_heights = [height_map[nc[0], nc[1]] for nc in neighbor_coords]\n    \n    if all([height < nh for nh in neighbor_heights]):\n      low_point_heights.append(height)\n    \nsum([h + 1 for h in low_point_heights])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n417\n```\n:::\n:::\n\n\n### Part 2\n\n>Next, you need to find the largest basins so you know what areas are most important to avoid.\n>\nA basin is all locations that eventually flow downward to a single low point. Therefore, every low point has a basin, although some basins are very small. Locations of height 9 do not count as being in any basin, and all other locations will always be part of exactly one basin.\n>\nThe size of a basin is the number of locations within the basin, including the low point. The example above has four basins.\n>\nWhat do you get if you multiply together the sizes of the three largest basins?\n\nMy strategy for part 2 is:\n\n* Loop over each point.\n    * If that point has a height <9, start a new basin.\n    * Rewrite that point with 9 (to prevent overcounting).\n    * For each of that points neighbors:\n        * If that point has a height <9, add it to the basin.\n        * Re-write that point with height 9.\n        * Add the points neighbors to a new list.\n    * Repeat the above loop with new neighbors until no neighbors remain.\n    * Compute the number of points in the basin.\n\nBasically, I'm finding points that are not 9, spreading out from those points, filling the basins with 9s, and counting those points along the way to get the basin size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbasin_size <- c()\n\nfor (row in 1:nrow(height_map)) {\n  for (col in 1:ncol(height_map)) {\n    height <- height_map[row, col]\n    if (height < 9) {\n      basin_points <- c(height)\n      height_map[row, col] <- 9\n      \n      neighbor_coords <- get_neighbor_coords(row, col,\n                                             nrow(height_map), ncol(height_map)) \n      \n      while (nrow(neighbor_coords) > 0) {\n        new_neighbor_coords <- matrix(nrow = 0, ncol = 2)\n        for (neighbor in 1:nrow(neighbor_coords)) {\n          nc <- neighbor_coords[neighbor, , drop = FALSE]\n          height <- height_map[nc]\n          if (height < 9) {\n            basin_points <- c(basin_points, height)\n            height_map[nc] <- 9\n            \n            new_neighbor_coords <- rbind(\n              new_neighbor_coords,\n              get_neighbor_coords(nc[1], nc[2],\n                                  nrow(height_map), ncol(height_map))\n            )\n          }\n        }\n        neighbor_coords <- new_neighbor_coords\n      }\n      basin_size <- c(basin_size, length(basin_points))\n    }\n  }\n}\n\nbasin_size\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1]  26  96  34  37  64   2  58  52   2  53  32  54  55  60   4   6  68  39\n [19]  14  69  30  22   5  21  33  64  38  96  45  21  15  29  16  89   3   7\n [37]  55  39   7  32   3  85  74  41  60  23  18  84   4  32  15  97   8   8\n [55]  50  15  24  66  20  68  45  84  42  67  68  70  10  16  49  63   4  19\n [73]   2  31  15  51   9  22  52  36   3  28  13   2  79  18  12   9  68   2\n [91]  83   4  39  95  75 115  41   7  79   2   4  27  85  26  25  87  16   8\n[109]   5  62  48   8  22  59  39   2  25  61  89  25  69  31  22  40   7  73\n[127]   8   4  38  50  23  57  30  18  41  92   4  69   2  48  86  20  52  94\n[145]  29  36   7  30  37  36  75  84  91  24  26   4  16 103  93  74  44   5\n[163]  31   6  51   5  15  83  93  73  18  94  22  61  72   8   8  53  53  45\n[181]  40  55   6  48  33  32  20   9   3  18  14  20  19   7   4   3   4   2\n```\n:::\n:::\n\n\nThe product of the three largest basins:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(basin_size, decreasing = TRUE)[1:3] %>% prod()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1148965\n```\n:::\n:::\n\n\nAnd in Python:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbasin_size = []\n\nfor row in range(height_map.shape[0]):\n  for col in range(height_map.shape[1]):\n    height = height_map[row, col]\n    \n    if height < 9:\n      basin_points = [height]\n      height_map[row, col] = 9\n      \n      neighbor_coords = get_neighbor_coords(row, col,\n                                            height_map.shape[0],\n                                            height_map.shape[1])\n      while len(neighbor_coords) > 0:\n        new_neighbor_coords = np.empty((0, 2), dtype = int)\n        \n        for nc in neighbor_coords:\n          height = height_map[nc[0], nc[1]]\n          if height < 9:\n            basin_points.append(height)\n            height_map[nc[0], nc[1]] = 9\n            \n            new_neighbor_coords = np.append(\n              new_neighbor_coords,\n              get_neighbor_coords(nc[0], nc[1],\n                                  height_map.shape[0], height_map.shape[1]),\n              axis = 0\n            )\n            \n        neighbor_coords = new_neighbor_coords \n        \n      basin_size.append(len(basin_points))\n\nbasin_size.sort(reverse = True)\nnp.prod(basin_size[0:3])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1148965\n```\n:::\n:::\n\n\n## Day 10: Syntax Scoring\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday10 <- read_lines(\"day10-input.txt\")\nhead(day10) %>% str_trunc(70)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"(<{([{([[[<{(<(){}>({}()))}[(<[]<>>{<>})[{{}()}<{}[]>]]><[[<{}{}>([...\"\n[2] \"<[<<{<[(([[[[<[][]>][(<>()){<>()}]]][<{<<>{}>(()<>)}><([<>{}]{()()}...\"\n[3] \"<(({(<{<({[<[[[]()][<>[]]]{{{}()}({}[])}>]{[{<<>[]>[()[]]}][[[{}[]]...\"\n[4] \"{{[{[[[{{{{{[([]())(<>())](<[]<>>{[]{}})}([[(){}]<<>()>]<<()()><{}{...\"\n[5] \"({([({([[({([{[]<>}]<<<>{}>[<>[]]>)})({{{[()[]]<()>}(([]<>)<[]()>>}...\"\n[6] \"<(((<<<{([[[<{()<>}{{}()}>[({}())([][])]]{{(()())(<>{})}(<{}><[]{}>...\"\n```\n:::\n:::\n\n\n### Part 1\n\n>\nYou ask the submarine to determine the best route out of the deep-sea cave, but it only replies:\n`Syntax error in navigation subsystem on line: all of them`\nAll of them?! The damage is worse than you thought. You bring up a copy of the navigation subsystem (your puzzle input).\n>\nThe navigation subsystem syntax is made of several lines containing chunks. There are one or more chunks on each line, and chunks contain zero or more other chunks. Adjacent chunks are not separated by any delimiter; if one chunk stops, the next chunk (if any) can immediately start. Every chunk must open and close with one of four legal pairs of matching characters:\n>\n    If a chunk opens with `(`, it must close with `)`.\n    If a chunk opens with `[`, it must close with `]`.\n    If a chunk opens with `{`, it must close with `}`.\n    If a chunk opens with `<`, it must close with `>`.\n>\nSo, `()` is a legal chunk that contains no other chunks, as is `[]`. More complex but valid chunks include `([])`, `{()()()}`, `<([{}])>`, `[<>({}){}[([])<>]]`, and even `(((((((((())))))))))`.\n>\nSome lines are incomplete, but others are corrupted. Find and discard the corrupted lines first.\n>\nA corrupted line is one where a chunk closes with the wrong character - that is, where the characters it opens and closes with do not form one of the four legal pairs listed above.\n>\nExamples of corrupted chunks include `(]`, `{()()()>`, `(((()))}`, and `<([]){()}[{}])`. Such a chunk can appear anywhere within a line, and its presence causes the whole line to be considered corrupted.\n>\nTo calculate the syntax error score for a line, take the first illegal character on the line and look it up in the following table:\n>\n    `)`: 3 points.\n    `]`: 57 points.\n    `}`: 1197 points.\n    `>`: 25137 points.\n>\nFind the first illegal character in each corrupted line of the navigation subsystem. What is the total syntax error score for those errors?\n\nI'll make heavy use of `stringr` and regular expressions to solve this problem.\nFirst, define a function that iterates over a line and determines if it is corrupt:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Regex representations of the character pairs (requires \\\\ to escape)\npairs <- c(\"\\\\(\\\\)\" = \"\", \"\\\\[\\\\]\" = \"\", \"\\\\{\\\\}\" = \"\", \"\\\\<\\\\>\" = \"\")\n\nremove_pairs <- function(line) {\n  repeat {\n    new_line <- line %>% str_replace_all(pairs)\n    if (new_line == line) return(new_line)\n    else line <- new_line\n  }\n}\n\nline <- \"([{<>}])[](<>)\"\nline_corrupt <- \"([{<>]])\"\n\nremove_pairs(line)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"\"\n```\n:::\n\n```{.r .cell-code}\nremove_pairs(line_corrupt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"([{]])\"\n```\n:::\n:::\n\n\nThen for corrupt lines, I need to find the location of the wrong closing characters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Regex representations of mismatched pairs \"[>\", \"(>\", \"{>\", \"[}\", etc.\nmismatched_pairs <- c(\"[\\\\(\\\\[\\\\{]\\\\>\",\n                      \"[\\\\(\\\\[\\\\<]\\\\}\",\n                      \"[\\\\(\\\\{\\\\<]\\\\]\",\n                      \"[\\\\[\\\\{\\\\<]\\\\)\")\n\nfind_corrupt_loc <- function(line_reduced) {\n  map_dfr(\n    mismatched_pairs,\n    ~remove_pairs(line_reduced) %>% str_locate(.x) %>% as.data.frame()\n  ) %>%\n    drop_na()\n}\n\ncorrupt_loc <- find_corrupt_loc(remove_pairs(line_corrupt))\ncorrupt_loc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  start end\n1     3   4\n```\n:::\n:::\n\n\nThen I use the `end` location (the smallest value to get the first occurrence) to determine which character is incorrect:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nremove_pairs(line_corrupt) %>%\n  str_sub(start = min(corrupt_loc$end), end = min(corrupt_loc$end))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"]\"\n```\n:::\n:::\n\n\nApply this to the full input:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday10_df <- tibble(line = day10) %>%\n  mutate(\n    line_reduced = map_chr(line, remove_pairs),\n    corrupt_loc = map(line_reduced, find_corrupt_loc)\n  )\n\ncorrupt_chars <- day10_df %>%\n  mutate(line_num = 1:n()) %>%\n  # Filter down to just corrupt lines\n  filter(map_int(corrupt_loc, nrow) > 0) %>%\n  transmute(\n    line_num,\n    corrupt_char = map2_chr(\n      line_reduced, corrupt_loc,\n      ~str_sub(.x, start = min(.y$end), end = min(.y$end))\n    )\n  )\ncorrupt_chars\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 47 × 2\n   line_num corrupt_char\n      <int> <chr>       \n 1        1 }           \n 2        5 >           \n 3        9 }           \n 4       12 }           \n 5       14 }           \n 6       16 ]           \n 7       17 }           \n 8       18 >           \n 9       21 ]           \n10       22 ]           \n# … with 37 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nFinally, add up the points of the characters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrupt_chars %>%\n  mutate(score = recode(corrupt_char,\n                        `)` = 3, `]` = 57, `}` = 1197, `>` = 25137)) %>%\n  pull(score) %>% sum()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 469755\n```\n:::\n:::\n\n\n### Part 2\n\n>\nNow, discard the corrupted lines. The remaining lines are incomplete.\n>\nIncomplete lines don't have any incorrect characters - instead, they're missing some closing characters at the end of the line. To repair the navigation subsystem, you just need to figure out the sequence of closing characters that complete all open chunks in the line.\n>\nYou can only use closing characters (`(`, `]`, `}`, or `>`), and you must add them in the correct order so that only legal pairs are formed and all chunks end up closed.\n>\nThe score is determined by considering the completion string character-by-character. Start with a total score of 0. Then, for each character, multiply the total score by 5 and then increase the total score by the point value given for the character in the following table:\n>\n    `)`: 1 point.\n    `]`: 2 points.\n    `}`: 3 points.\n    `>`: 4 points.\n>\nAutocomplete tools are an odd bunch: the winner is found by sorting all of the scores and then taking the middle score. (There will always be an odd number of scores to consider.) In this example, the middle score is 288957 because there are the same number of scores smaller and larger than it.\n>\nFind the completion string for each incomplete line, score the completion strings, and sort the scores. What is the middle score?\n\nFrom part 1, we have these incomplete (and non-corrupt) lines:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nday10_incomplete <- day10_df %>%\n  filter(map_int(corrupt_loc, nrow) == 0) %>%\n  select(-corrupt_loc)\nglimpse(day10_incomplete)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 47\nColumns: 2\n$ line         <chr> \"<[<<{<[(([[[[<[][]>][(<>()){<>()}]]][<{<<>{}>(()<>)}><([…\n$ line_reduced <chr> \"<[<<{<[({{<{\", \"<(({(<{<((\", \"{{[{[[[{{((<<({\", \"<(((<<<…\n```\n:::\n:::\n\n\nAs expected, we have an odd number of lines so we can get a middle score.\nBecause I've already reduced the `line`s down to `line_reduced` without matching pairs, I can simply reverse the order, and count the scores.\nFor example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreversed_chars <- remove_pairs(\"[({(<(())[]>[[{[]{<()<>>\") %>%\n  strsplit(\"\") %>%\n  unlist() %>%\n  rev()\n \ntotal_score <- 0\nfor (char in reversed_chars) {\n  total_score <- total_score * 5\n  # No need to replace the opening with closing characters\n  total_score <- total_score + switch(char, `(` = 1, `[` = 2, `{` = 3, `<` = 4)\n}\ntotal_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 288957\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nday10_incomplete <- day10_incomplete %>%\n  mutate(\n    total_score = map_dbl(\n      line_reduced,\n      ~{\n        reversed_chars <- str_split(.x, \"\") %>% unlist() %>% rev()\n        \n        total_score <- 0\n        for (char in reversed_chars) {\n          total_score <- total_score * 5\n          total_score <- total_score + switch(char, `(` = 1, `[` = 2, `{` = 3, `<` = 4)\n        }\n        total_score\n      }\n    )\n  )\nsort(day10_incomplete$total_score)[(nrow(day10_incomplete) + 1) / 2]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2762335572\n```\n:::\n:::\n\n\n## Stats\n\nMy personal stats for this period:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble::tribble(\n  ~Part, ~Day, ~Time, ~Rank,\n  1, 10, \"11:11:48\", 34029,\n  2, 10, \"11:25:31\", 32045,\n  1, 9, \"14:58:48\", 42395,\n  2, 9, \"16:04:08\", 33905,\n  1, 8, \"16:37:13\", 49102,\n  2, 8, \"16:55:20\", 34954,\n  1, 7, \"11:23:20\", 45816,\n  2, 7, \"11:42:48\", 43886,\n  1, 6, \"10:38:42\", 41671,\n  2, 6, \"10:58:31\", 34999\n) %>%\n  pivot_wider(names_from = Part, values_from = c(Time, Rank),\n              names_glue = \"Part {Part}_{.value}\") %>%\n  mutate(\n    `Time between parts` = as.numeric(hms(`Part 2_Time`) - hms(`Part 1_Time`),\n                                      \"minutes\") %>% round(1)\n  ) %>%\n  gt() %>%\n  tab_spanner_delim(delim = \"_\", split = \"first\") %>%\n  sub_missing(columns = \"Time between parts\", missing_text = \"\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"xedkspmaaj\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#xedkspmaaj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xedkspmaaj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xedkspmaaj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xedkspmaaj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xedkspmaaj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xedkspmaaj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xedkspmaaj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xedkspmaaj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xedkspmaaj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xedkspmaaj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xedkspmaaj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xedkspmaaj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xedkspmaaj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xedkspmaaj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xedkspmaaj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xedkspmaaj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xedkspmaaj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xedkspmaaj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xedkspmaaj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xedkspmaaj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xedkspmaaj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xedkspmaaj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xedkspmaaj .gt_left {\n  text-align: left;\n}\n\n#xedkspmaaj .gt_center {\n  text-align: center;\n}\n\n#xedkspmaaj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xedkspmaaj .gt_font_normal {\n  font-weight: normal;\n}\n\n#xedkspmaaj .gt_font_bold {\n  font-weight: bold;\n}\n\n#xedkspmaaj .gt_font_italic {\n  font-style: italic;\n}\n\n#xedkspmaaj .gt_super {\n  font-size: 65%;\n}\n\n#xedkspmaaj .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#xedkspmaaj .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#xedkspmaaj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xedkspmaaj .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#xedkspmaaj .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#xedkspmaaj .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\">Day</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\">\n        <span class=\"gt_column_spanner\">Time</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\">\n        <span class=\"gt_column_spanner\">Rank</span>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\">Time between parts</th>\n    </tr>\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">Part 1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">Part 2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Part 1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Part 2</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">10</td>\n<td class=\"gt_row gt_left\">11:11:48</td>\n<td class=\"gt_row gt_left\">11:25:31</td>\n<td class=\"gt_row gt_right\">34029</td>\n<td class=\"gt_row gt_right\">32045</td>\n<td class=\"gt_row gt_right\">13.7</td></tr>\n    <tr><td class=\"gt_row gt_right\">9</td>\n<td class=\"gt_row gt_left\">14:58:48</td>\n<td class=\"gt_row gt_left\">16:04:08</td>\n<td class=\"gt_row gt_right\">42395</td>\n<td class=\"gt_row gt_right\">33905</td>\n<td class=\"gt_row gt_right\">65.3</td></tr>\n    <tr><td class=\"gt_row gt_right\">8</td>\n<td class=\"gt_row gt_left\">16:37:13</td>\n<td class=\"gt_row gt_left\">16:55:20</td>\n<td class=\"gt_row gt_right\">49102</td>\n<td class=\"gt_row gt_right\">34954</td>\n<td class=\"gt_row gt_right\">18.1</td></tr>\n    <tr><td class=\"gt_row gt_right\">7</td>\n<td class=\"gt_row gt_left\">11:23:20</td>\n<td class=\"gt_row gt_left\">11:42:48</td>\n<td class=\"gt_row gt_right\">45816</td>\n<td class=\"gt_row gt_right\">43886</td>\n<td class=\"gt_row gt_right\">19.5</td></tr>\n    <tr><td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_left\">10:38:42</td>\n<td class=\"gt_row gt_left\">10:58:31</td>\n<td class=\"gt_row gt_right\">41671</td>\n<td class=\"gt_row gt_right\">34999</td>\n<td class=\"gt_row gt_right\">19.8</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## Reproducibility {.appendix .unlisted}\n\n<details><summary>Session info</summary>\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n setting  value\n version  R version 4.2.1 (2022-06-23 ucrt)\n os       Windows 10 x64 (build 19044)\n system   x86_64, mingw32\n ui       RTerm\n language (EN)\n collate  English_Canada.utf8\n ctype    English_Canada.utf8\n tz       America/Curacao\n date     2022-09-19\n pandoc   2.18 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)\n```\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"package\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"ondiskversion\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"loadedversion\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"path\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"loadedpath\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"attached\"],\"name\":[6],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"is_base\"],\"name\":[7],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"date\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"source\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"md5ok\"],\"name\":[10],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"library\"],\"name\":[11],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"assertthat\",\"2\":\"0.2.1\",\"3\":\"0.2.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/assertthat\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/assertthat\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-03-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"assertthat\"},{\"1\":\"backports\",\"2\":\"1.4.1\",\"3\":\"1.4.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/backports\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/backports\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-13\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"backports\"},{\"1\":\"bit\",\"2\":\"4.0.4\",\"3\":\"4.0.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/bit\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/bit\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-08-04\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"bit\"},{\"1\":\"bit64\",\"2\":\"4.0.5\",\"3\":\"4.0.5\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/bit64\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/bit64\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-08-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"bit64\"},{\"1\":\"broom\",\"2\":\"1.0.0\",\"3\":\"1.0.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/broom\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/broom\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-01\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"broom\"},{\"1\":\"cachem\",\"2\":\"1.0.6\",\"3\":\"1.0.6\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cachem\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cachem\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-19\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"cachem\"},{\"1\":\"callr\",\"2\":\"3.7.1\",\"3\":\"3.7.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/callr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/callr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-13\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"callr\"},{\"1\":\"cellranger\",\"2\":\"1.1.0\",\"3\":\"1.1.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cellranger\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cellranger\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2016-07-27\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"cellranger\"},{\"1\":\"checkmate\",\"2\":\"2.1.0\",\"3\":\"2.1.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/checkmate\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/checkmate\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"checkmate\"},{\"1\":\"cli\",\"2\":\"3.3.0\",\"3\":\"3.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cli\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cli\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"cli\"},{\"1\":\"colorspace\",\"2\":\"2.0.3\",\"3\":\"2.0-3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/colorspace\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/colorspace\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"colorspace\"},{\"1\":\"crayon\",\"2\":\"1.5.1\",\"3\":\"1.5.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/crayon\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/crayon\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"crayon\"},{\"1\":\"DBI\",\"2\":\"1.1.3\",\"3\":\"1.1.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/DBI\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/DBI\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-06-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"DBI\"},{\"1\":\"dbplyr\",\"2\":\"2.2.1\",\"3\":\"2.2.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dbplyr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dbplyr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-06-27\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"dbplyr\"},{\"1\":\"devtools\",\"2\":\"2.4.4\",\"3\":\"2.4.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/devtools\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/devtools\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-20\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"devtools\"},{\"1\":\"digest\",\"2\":\"0.6.29\",\"3\":\"0.6.29\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/digest\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/digest\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-01\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"digest\"},{\"1\":\"dplyr\",\"2\":\"1.0.9\",\"3\":\"1.0.9\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dplyr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dplyr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-04-28\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"dplyr\"},{\"1\":\"ellipsis\",\"2\":\"0.3.2\",\"3\":\"0.3.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ellipsis\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ellipsis\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-04-29\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ellipsis\"},{\"1\":\"evaluate\",\"2\":\"0.15\",\"3\":\"0.15\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/evaluate\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/evaluate\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"evaluate\"},{\"1\":\"fansi\",\"2\":\"1.0.3\",\"3\":\"1.0.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fansi\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fansi\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"fansi\"},{\"1\":\"fastmap\",\"2\":\"1.1.0\",\"3\":\"1.1.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fastmap\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fastmap\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-01-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"fastmap\"},{\"1\":\"forcats\",\"2\":\"0.5.1\",\"3\":\"0.5.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/forcats\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/forcats\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2021-01-27\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"forcats\"},{\"1\":\"fs\",\"2\":\"1.5.2\",\"3\":\"1.5.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fs\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fs\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-08\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"fs\"},{\"1\":\"gargle\",\"2\":\"1.2.0\",\"3\":\"1.2.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gargle\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gargle\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-07-02\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"gargle\"},{\"1\":\"generics\",\"2\":\"0.1.3\",\"3\":\"0.1.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/generics\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/generics\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"generics\"},{\"1\":\"ggplot2\",\"2\":\"3.3.6\",\"3\":\"3.3.6\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ggplot2\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ggplot2\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-05-03\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ggplot2\"},{\"1\":\"glue\",\"2\":\"1.6.2\",\"3\":\"1.6.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/glue\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/glue\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"glue\"},{\"1\":\"googledrive\",\"2\":\"2.0.0\",\"3\":\"2.0.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/googledrive\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/googledrive\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-07-08\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"googledrive\"},{\"1\":\"googlesheets4\",\"2\":\"1.0.0\",\"3\":\"1.0.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/googlesheets4\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/googlesheets4\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-07-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"googlesheets4\"},{\"1\":\"gt\",\"2\":\"0.6.0\",\"3\":\"0.6.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gt\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gt\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-05-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"gt\"},{\"1\":\"gtable\",\"2\":\"0.3.0\",\"3\":\"0.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gtable\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gtable\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-03-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"gtable\"},{\"1\":\"haven\",\"2\":\"2.5.0\",\"3\":\"2.5.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/haven\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/haven\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-15\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"haven\"},{\"1\":\"here\",\"2\":\"1.0.1\",\"3\":\"1.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/here\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/here\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2020-12-13\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"here\"},{\"1\":\"hms\",\"2\":\"1.1.1\",\"3\":\"1.1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/hms\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/hms\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"hms\"},{\"1\":\"htmltools\",\"2\":\"0.5.2\",\"3\":\"0.5.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/htmltools\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/htmltools\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"NA\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"htmltools\"},{\"1\":\"htmlwidgets\",\"2\":\"1.5.4\",\"3\":\"1.5.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/htmlwidgets\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/htmlwidgets\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-08\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"htmlwidgets\"},{\"1\":\"httpuv\",\"2\":\"1.6.5\",\"3\":\"1.6.5\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/httpuv\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/httpuv\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-01-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"httpuv\"},{\"1\":\"httr\",\"2\":\"1.4.3\",\"3\":\"1.4.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/httr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/httr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-05-04\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"httr\"},{\"1\":\"jsonlite\",\"2\":\"1.8.0\",\"3\":\"1.8.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/jsonlite\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/jsonlite\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"jsonlite\"},{\"1\":\"knitr\",\"2\":\"1.39\",\"3\":\"1.39\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/knitr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/knitr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"knitr\"},{\"1\":\"later\",\"2\":\"1.3.0\",\"3\":\"1.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/later\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/later\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"later\"},{\"1\":\"lattice\",\"2\":\"0.20.45\",\"3\":\"0.20-45\",\"4\":\"C:/Program Files/R/R-4.2.1/library/lattice\",\"5\":\"C:/Program Files/R/R-4.2.1/library/lattice\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"NA\",\"11\":\"C:/Program Files/R/R-4.2.1/library\",\"_rn_\":\"lattice\"},{\"1\":\"lifecycle\",\"2\":\"1.0.1\",\"3\":\"1.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/lifecycle\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/lifecycle\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"lifecycle\"},{\"1\":\"lubridate\",\"2\":\"1.8.0\",\"3\":\"1.8.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/lubridate\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/lubridate\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2021-10-07\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"lubridate\"},{\"1\":\"magrittr\",\"2\":\"2.0.3\",\"3\":\"2.0.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/magrittr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/magrittr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"magrittr\"},{\"1\":\"Matrix\",\"2\":\"1.4.1\",\"3\":\"1.4-1\",\"4\":\"C:/Program Files/R/R-4.2.1/library/Matrix\",\"5\":\"C:/Program Files/R/R-4.2.1/library/Matrix\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-23\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"NA\",\"11\":\"C:/Program Files/R/R-4.2.1/library\",\"_rn_\":\"Matrix\"},{\"1\":\"memoise\",\"2\":\"2.0.1\",\"3\":\"2.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/memoise\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/memoise\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"memoise\"},{\"1\":\"mime\",\"2\":\"0.12\",\"3\":\"0.12\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/mime\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/mime\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-28\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"mime\"},{\"1\":\"miniUI\",\"2\":\"0.1.1.1\",\"3\":\"0.1.1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/miniUI\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/miniUI\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2018-05-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"miniUI\"},{\"1\":\"modelr\",\"2\":\"0.1.8\",\"3\":\"0.1.8\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/modelr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/modelr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-05-19\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"modelr\"},{\"1\":\"munsell\",\"2\":\"0.5.0\",\"3\":\"0.5.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/munsell\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/munsell\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2018-06-12\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"munsell\"},{\"1\":\"pillar\",\"2\":\"1.8.0\",\"3\":\"1.8.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pillar\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pillar\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"pillar\"},{\"1\":\"pkgbuild\",\"2\":\"1.3.1\",\"3\":\"1.3.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgbuild\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgbuild\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-20\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"pkgbuild\"},{\"1\":\"pkgconfig\",\"2\":\"2.0.3\",\"3\":\"2.0.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgconfig\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgconfig\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-09-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"pkgconfig\"},{\"1\":\"pkgload\",\"2\":\"1.3.0\",\"3\":\"1.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgload\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgload\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-06-27\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"pkgload\"},{\"1\":\"png\",\"2\":\"0.1.7\",\"3\":\"0.1-7\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/png\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/png\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2013-12-03\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"png\"},{\"1\":\"prettyunits\",\"2\":\"1.1.1\",\"3\":\"1.1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/prettyunits\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/prettyunits\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-01-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"prettyunits\"},{\"1\":\"processx\",\"2\":\"3.7.0\",\"3\":\"3.7.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/processx\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/processx\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-07\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"processx\"},{\"1\":\"profvis\",\"2\":\"0.3.7\",\"3\":\"0.3.7\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/profvis\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/profvis\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-11-02\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"profvis\"},{\"1\":\"promises\",\"2\":\"1.2.0.1\",\"3\":\"1.2.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/promises\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/promises\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-02-11\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"promises\"},{\"1\":\"ps\",\"2\":\"1.7.1\",\"3\":\"1.7.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ps\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ps\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-06-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ps\"},{\"1\":\"purrr\",\"2\":\"0.3.4\",\"3\":\"0.3.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/purrr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/purrr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2020-04-17\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"purrr\"},{\"1\":\"R6\",\"2\":\"2.5.1\",\"3\":\"2.5.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/R6\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/R6\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-19\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"R6\"},{\"1\":\"Rcpp\",\"2\":\"1.0.9\",\"3\":\"1.0.9\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/Rcpp\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/Rcpp\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-08\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"Rcpp\"},{\"1\":\"readr\",\"2\":\"2.1.2\",\"3\":\"2.1.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/readr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/readr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-01-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"readr\"},{\"1\":\"readxl\",\"2\":\"1.4.0\",\"3\":\"1.4.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/readxl\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/readxl\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-28\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"readxl\"},{\"1\":\"remotes\",\"2\":\"2.4.2\",\"3\":\"2.4.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/remotes\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/remotes\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"remotes\"},{\"1\":\"reprex\",\"2\":\"2.0.1\",\"3\":\"2.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/reprex\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/reprex\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"reprex\"},{\"1\":\"reticulate\",\"2\":\"1.26\",\"3\":\"1.26\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/reticulate\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/reticulate\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-08-31\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"reticulate\"},{\"1\":\"rlang\",\"2\":\"1.0.4\",\"3\":\"1.0.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rlang\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rlang\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-12\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rlang\"},{\"1\":\"rmarkdown\",\"2\":\"2.14\",\"3\":\"2.14\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rmarkdown\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rmarkdown\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rmarkdown\"},{\"1\":\"rprojroot\",\"2\":\"2.0.3\",\"3\":\"2.0.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rprojroot\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rprojroot\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-02\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rprojroot\"},{\"1\":\"rstudioapi\",\"2\":\"0.13\",\"3\":\"0.13\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rstudioapi\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rstudioapi\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-11-12\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rstudioapi\"},{\"1\":\"rvest\",\"2\":\"1.0.2\",\"3\":\"1.0.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rvest\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rvest\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-10-16\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rvest\"},{\"1\":\"sass\",\"2\":\"0.4.2\",\"3\":\"0.4.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/sass\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/sass\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-16\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"sass\"},{\"1\":\"scales\",\"2\":\"1.2.0\",\"3\":\"1.2.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/scales\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/scales\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-13\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"scales\"},{\"1\":\"sessioninfo\",\"2\":\"1.2.2\",\"3\":\"1.2.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/sessioninfo\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/sessioninfo\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-06\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"sessioninfo\"},{\"1\":\"shiny\",\"2\":\"1.7.2\",\"3\":\"1.7.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/shiny\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/shiny\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-19\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"shiny\"},{\"1\":\"stringi\",\"2\":\"1.7.8\",\"3\":\"1.7.8\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/stringi\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/stringi\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-11\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"stringi\"},{\"1\":\"stringr\",\"2\":\"1.4.0\",\"3\":\"1.4.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/stringr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/stringr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2019-02-10\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"stringr\"},{\"1\":\"tibble\",\"2\":\"3.1.8\",\"3\":\"3.1.8\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tibble\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tibble\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-07-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tibble\"},{\"1\":\"tidyr\",\"2\":\"1.2.0\",\"3\":\"1.2.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-02-01\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tidyr\"},{\"1\":\"tidyselect\",\"2\":\"1.1.2\",\"3\":\"1.1.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyselect\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyselect\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tidyselect\"},{\"1\":\"tidyverse\",\"2\":\"1.3.2\",\"3\":\"1.3.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyverse\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyverse\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-07-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tidyverse\"},{\"1\":\"tzdb\",\"2\":\"0.3.0\",\"3\":\"0.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tzdb\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tzdb\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-28\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tzdb\"},{\"1\":\"urlchecker\",\"2\":\"1.0.1\",\"3\":\"1.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/urlchecker\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/urlchecker\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"urlchecker\"},{\"1\":\"usethis\",\"2\":\"2.1.6\",\"3\":\"2.1.6\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/usethis\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/usethis\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-05-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"usethis\"},{\"1\":\"utf8\",\"2\":\"1.2.2\",\"3\":\"1.2.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/utf8\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/utf8\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-07-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"utf8\"},{\"1\":\"vctrs\",\"2\":\"0.4.1\",\"3\":\"0.4.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/vctrs\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/vctrs\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-13\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"vctrs\"},{\"1\":\"vroom\",\"2\":\"1.5.7\",\"3\":\"1.5.7\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/vroom\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/vroom\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"vroom\"},{\"1\":\"withr\",\"2\":\"2.5.0\",\"3\":\"2.5.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/withr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/withr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-03\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"withr\"},{\"1\":\"xfun\",\"2\":\"0.31\",\"3\":\"0.31\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xfun\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xfun\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-05-10\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"xfun\"},{\"1\":\"xml2\",\"2\":\"1.3.3\",\"3\":\"1.3.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xml2\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xml2\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"xml2\"},{\"1\":\"xtable\",\"2\":\"1.8.4\",\"3\":\"1.8-4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xtable\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xtable\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-04-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"xtable\"},{\"1\":\"yaml\",\"2\":\"2.3.5\",\"3\":\"2.3.5\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/yaml\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/yaml\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-21\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"yaml\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\npython:         C:/Users/tdunn/Documents/.virtualenvs/r-reticulate/Scripts/python.exe\nlibpython:      C:/Users/tdunn/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python39.dll\npythonhome:     C:/Users/tdunn/Documents/.virtualenvs/r-reticulate\nversion:        3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]\nArchitecture:   64bit\nnumpy:          C:/Users/tdunn/Documents/.virtualenvs/r-reticulate/Lib/site-packages/numpy\nnumpy_version:  1.23.3\n\nNOTE: Python version was forced by use_python function\n```\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"package\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"version\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"requirement\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"contourpy\",\"2\":\"1.0.5\",\"3\":\"contourpy==1.0.5\"},{\"1\":\"cycler\",\"2\":\"0.11.0\",\"3\":\"cycler==0.11.0\"},{\"1\":\"fonttools\",\"2\":\"4.37.2\",\"3\":\"fonttools==4.37.2\"},{\"1\":\"kiwisolver\",\"2\":\"1.4.4\",\"3\":\"kiwisolver==1.4.4\"},{\"1\":\"matplotlib\",\"2\":\"3.6.0\",\"3\":\"matplotlib==3.6.0\"},{\"1\":\"numpy\",\"2\":\"1.23.3\",\"3\":\"numpy==1.23.3\"},{\"1\":\"packaging\",\"2\":\"21.3\",\"3\":\"packaging==21.3\"},{\"1\":\"pandas\",\"2\":\"1.4.4\",\"3\":\"pandas==1.4.4\"},{\"1\":\"Pillow\",\"2\":\"9.2.0\",\"3\":\"Pillow==9.2.0\"},{\"1\":\"pyparsing\",\"2\":\"3.0.9\",\"3\":\"pyparsing==3.0.9\"},{\"1\":\"python-dateutil\",\"2\":\"2.8.2\",\"3\":\"python-dateutil==2.8.2\"},{\"1\":\"pytz\",\"2\":\"2022.2.1\",\"3\":\"pytz==2022.2.1\"},{\"1\":\"scipy\",\"2\":\"1.9.1\",\"3\":\"scipy==1.9.1\"},{\"1\":\"six\",\"2\":\"1.16.0\",\"3\":\"six==1.16.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n</details>\n\n<details><summary>Git repository</summary>\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\nLocal:    main C:/Users/tdunn/Documents/tdunn-quarto\nRemote:   main @ origin (https://github.com/taylordunn/tdunn-quarto.git)\nHead:     [562f48a] 2022-09-20: Turn off bold for \"Extension\"\n```\n:::\n:::\n\n\n</details>\n\n\n\n<a href=\"https://github.com/taylordunn/tdunn-quarto/tree/main/posts/2021-12-06-advent-of-code-2021-days-6-10\">Source code</a>, <a href=\"https://github.com/taylordunn/tdunn-quarto/tree/main/posts/2021-12-06-advent-of-code-2021-days-6-10/renv.lock\">R environment</a>\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}