project:
  type: website

website:
  title: "tdunn"
  site-url: https://tdunn.ca
  repo-url: https://github.com/taylordunn/tdunn-quarto
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    creator: "@TDunn12"
    card-style: summary_large_image
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/taylordunn
      - icon: twitter
        href: https://twitter.com/TDunn12
  google-analytics: "UA-196523553-1"
format:
  html:
    theme: flatly
    highlight-style: nord
    code-link: false
    mainfont: "Roboto Condensed"
    monofont: "Fira Code"
