{
  "hash": "a6359075a0fed1cdad31a3fc373bd683",
  "result": {
    "markdown": "---\ntitle: \"Ordinal regression in R: part 1\"\ndescription: |\n  A theoretical and applied walkthrough of ordinal regression.\n  Part 1: the frequentist approach with `ordinal`.\ndate: 2020-03-15\nparams:\n  date: 2020-03-15\n  slug: \"ordinal-regression-in-r-part-1\"\ncategories:\n  - R\n  - regression\n  - ordinal\n  - frequentist statistics\nimage: preview.png\nbibliography: references.bib\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R setup\"}\nlibrary(tidyverse)\nlibrary(dunnr)\nlibrary(gt)\nlibrary(broom)\nlibrary(patchwork)\n\nextrafont::loadfonts(device = \"win\", quiet = TRUE)\ntheme_set(theme_td())\nset_geom_fonts()\nset_palette()\n\nwine_red <- \"#58181F\"\nupdate_geom_defaults(\"point\", list(color = wine_red))\nupdate_geom_defaults(\"line\", list(color = wine_red))\n```\n:::\n\n\nThe purpose of this post is to learn more about ordinal regression models (a.k.a. cumulative link, proportional odds, ordered logit models, etc.) and practice their implementation in R.\nThis is part 1, where I'll be taking the frequentist approach via the [`ordinal` package](https://cran.r-project.org/web/packages/ordinal/index.html).\nThere are other options, like `MASS::polr`, but two features in particular drew me to `ordinal`: (1) it allows for random effects, and (2) it has [`broom::tidy` methods](https://rdrr.io/cran/broom/man/ordinal_tidiers.html) available.\n\nParticularly, I'll be following along with\n\n* this excellent [primer](https://r-forge.r-project.org/scm/viewvc.php/*checkout*/pkg/ordinal/inst/doc/primer.pdf?revision=66&root=ordinal&pathrev=69) which includes theory and application, and\n* this [vignette](https://cran.r-project.org/web/packages/ordinal/vignettes/clmm2_tutorial.pdf) which is a tutorial on incorporating random effects.\n\n## Setup\n\nImport `ordinal`, and the included data set `wine`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ordinal)\ndata(wine)\nwine <- as_tibble(wine)\nglimpse(wine)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 72\nColumns: 6\n$ response <dbl> 36, 48, 47, 67, 77, 60, 83, 90, 17, 22, 14, 50, 30, 51, 90, 7…\n$ rating   <ord> 2, 3, 3, 4, 4, 4, 5, 5, 1, 2, 1, 3, 2, 3, 5, 4, 2, 3, 3, 2, 5…\n$ temp     <fct> cold, cold, cold, cold, warm, warm, warm, warm, cold, cold, c…\n$ contact  <fct> no, no, yes, yes, no, no, yes, yes, no, no, yes, yes, no, no,…\n$ bottle   <fct> 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5…\n$ judge    <fct> 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3…\n```\n:::\n:::\n\n\n`wine` is a data set from @Randall1989 of wine bitterness ratings from multiple judges.\nThe variables are as follows:\n\n* Outcome:\n    * `response`: wine bitterness rating on a 0-100 scale\n    * `rating`: ordered factor with 5 levels (grouped version of `response`) with 1 = \"least bitter\" and 5 = \"most bitter\"\n* Treatment factors:\n    * `temp`: temperature during wine production (cold and warm)\n    * `contact`: contact between juice and skins during wine production (no and yes)\n* Random effects\n    * `bottle` with 8 levels\n    * `judge` with 9 levels\n\nRelationship between `response` and `rating`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine %>%\n  ggplot(aes(y = rating, x = response)) +\n  geom_boxplot(width = 0.5) +\n  geom_jitter(alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-in-r-part-1_files/figure-html/unnamed-chunk-4-1.png){width=480}\n:::\n:::\n\n\nNote that there is no overlap between the levels.\n\nThere are 72 total observations with the following ratings distribution by treatment and random effects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine %>%\n  transmute(temp, contact, bottle, judge, rating = as.numeric(rating)) %>%\n  pivot_wider(names_from = judge, values_from = rating) %>%\n  gt() %>%\n  tab_spanner(columns = `1`:`9`, label = \"judge\") %>%\n  data_color(\n    columns = `1`:`9`,\n    colors = scales::col_numeric(\n      palette = c(\"white\", wine_red), domain = c(1, 5)\n    )\n  )\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"plueupvuic\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#plueupvuic .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#plueupvuic .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#plueupvuic .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#plueupvuic .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#plueupvuic .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plueupvuic .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#plueupvuic .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#plueupvuic .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#plueupvuic .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#plueupvuic .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#plueupvuic .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#plueupvuic .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#plueupvuic .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#plueupvuic .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#plueupvuic .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#plueupvuic .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#plueupvuic .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plueupvuic .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#plueupvuic .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#plueupvuic .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plueupvuic .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#plueupvuic .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#plueupvuic .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plueupvuic .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plueupvuic .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#plueupvuic .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#plueupvuic .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plueupvuic .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#plueupvuic .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plueupvuic .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#plueupvuic .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plueupvuic .gt_left {\n  text-align: left;\n}\n\n#plueupvuic .gt_center {\n  text-align: center;\n}\n\n#plueupvuic .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#plueupvuic .gt_font_normal {\n  font-weight: normal;\n}\n\n#plueupvuic .gt_font_bold {\n  font-weight: bold;\n}\n\n#plueupvuic .gt_font_italic {\n  font-style: italic;\n}\n\n#plueupvuic .gt_super {\n  font-size: 65%;\n}\n\n#plueupvuic .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#plueupvuic .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#plueupvuic .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#plueupvuic .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#plueupvuic .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#plueupvuic .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\">temp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\">contact</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\">bottle</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"9\">\n        <span class=\"gt_column_spanner\">judge</span>\n      </th>\n    </tr>\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">6</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">7</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">8</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">9</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_center\">cold</td>\n<td class=\"gt_row gt_center\">no</td>\n<td class=\"gt_row gt_center\">1</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #FFFFFF; color: #000000;\">1</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #FFFFFF; color: #000000;\">1</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #FFFFFF; color: #000000;\">1</td></tr>\n    <tr><td class=\"gt_row gt_center\">cold</td>\n<td class=\"gt_row gt_center\">no</td>\n<td class=\"gt_row gt_center\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #FFFFFF; color: #000000;\">1</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td></tr>\n    <tr><td class=\"gt_row gt_center\">cold</td>\n<td class=\"gt_row gt_center\">yes</td>\n<td class=\"gt_row gt_center\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #FFFFFF; color: #000000;\">1</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td></tr>\n    <tr><td class=\"gt_row gt_center\">cold</td>\n<td class=\"gt_row gt_center\">yes</td>\n<td class=\"gt_row gt_center\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td></tr>\n    <tr><td class=\"gt_row gt_center\">warm</td>\n<td class=\"gt_row gt_center\">no</td>\n<td class=\"gt_row gt_center\">5</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #58181F; color: #FFFFFF;\">5</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td></tr>\n    <tr><td class=\"gt_row gt_center\">warm</td>\n<td class=\"gt_row gt_center\">no</td>\n<td class=\"gt_row gt_center\">6</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #58181F; color: #FFFFFF;\">5</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td></tr>\n    <tr><td class=\"gt_row gt_center\">warm</td>\n<td class=\"gt_row gt_center\">yes</td>\n<td class=\"gt_row gt_center\">7</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #58181F; color: #FFFFFF;\">5</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #58181F; color: #FFFFFF;\">5</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #58181F; color: #FFFFFF;\">5</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #58181F; color: #FFFFFF;\">5</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #D7C1C1; color: #000000;\">2</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td></tr>\n    <tr><td class=\"gt_row gt_center\">warm</td>\n<td class=\"gt_row gt_center\">yes</td>\n<td class=\"gt_row gt_center\">8</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #58181F; color: #FFFFFF;\">5</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #AD8686; color: #000000;\">3</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td>\n<td class=\"gt_row gt_right\" style=\"background-color: #834F4F; color: #FFFFFF;\">4</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nSo each `bottle` had a particular `temp` and `contact` (2 bottles for each of the 4 combinations), and each `judge` rated the bitterness each bottle.\n\nBefore modeling, can we see a clear effect of `temp` and `contact`?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine %>%\n  count(contact, rating, temp) %>%\n  mutate(temp = fct_rev(temp)) %>%\n  ggplot(aes(x = temp, y = rating, color = temp)) +\n  geom_point(aes(group = temp, size = n)) +\n  facet_wrap(~contact, scales = \"free_x\",\n             labeller = labeller(contact = label_both)) +\n  scale_size(breaks = c(1, 2, 4, 6, 8)) +\n  add_facet_borders()\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-in-r-part-1_files/figure-html/unnamed-chunk-6-1.png){width=480}\n:::\n:::\n\n\nAt a glance, it looks like the `temp` = warm and `contact` = yes is associated with higher `rating`s.\n\n## The cumulative link model\n\n### Theory\n\nThe ordinal response $y_i$ falls into response category $j$ (out of $J$ total) with probability $\\pi_{ij}$.\nThe cumulative probabilities are defined:\n\n\n$$\nP(y_i \\leq j) = \\pi_{i1} + \\dots + \\pi_{ij}.\n$$\n\n\nAs an oversimplification, suppose that each probability $\\pi_{ij}$ is equal to the proportion of that response in the `wine` data.\nThen the cumulative \"probability\" can be visualized:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine_prop <- wine %>%\n  count(rating) %>%\n  mutate(p = n / sum(n), cumsum_p = cumsum(p))\n\n(\n  ggplot(wine_prop, aes(x = rating, y = p)) +\n    geom_col(fill = wine_red) +\n    scale_y_continuous(labels = scales::percent, expand = c(0, 0)) +\n    labs(x = \"j\", y = \"proportion\")\n) +\n  (\n    ggplot(wine_prop, aes(x = as.integer(rating), y = cumsum_p)) +\n      geom_point(size = 2) +\n      geom_line(size = 1) +\n      labs(x = \"j\", y = \"cumulative proportion\")\n  ) +\n  (\n    ggplot(wine_prop,\n        aes(x = as.integer(rating), y = log(cumsum_p) - log(1 - cumsum_p))) +\n      geom_point(size = 2) +\n      geom_line(size = 1) +\n      labs(x = \"j\", y = \"logit(cumulative proportion)\")\n  )\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-in-r-part-1_files/figure-html/unnamed-chunk-7-1.png){width=768}\n:::\n:::\n\n\nWe will explore other links, but first the most common, the logit link, which is depicted in the right-most panel of the above figure:\n\n\n$$\n\\text{logit} (P(y_i \\leq j) = \\log \\frac{P(y_i \\leq j)}{1 - P(y_i \\leq j)}\n$$\n\n\nNote that the above function is defined for all but the last category $j = J$, because $1 - P(Y_i \\leq J) = 1 - 1 = 0$.\n\nFor the `wine` data, where we have $J$ = 5 rating categories, we will build up to the following mixed effects model:\n\n\n$$\n\\begin{align}\n\\text{logit}(p(y_i \\leq j)) &= \\theta_j - \\beta_1 \\text{temp}_i - \\beta_2 \\text{contact}_i - u( \\text{judge}_i) \\\\\ni &= 1, \\dots n \\; \\; \\; \\; \\; \\; j = 1, \\dots, J - 1\n\\end{align}\n$$\n\n\nwhere $\\theta_j$ is called the threshold parameter, or cutpoint, of category $j$.\nThese thresholds can also be thought of as $J-1$ = 4 intercepts.\nNote that the fixed effect parameters $\\beta_1$ and $\\beta_2$ are independent of $j$, so each $\\beta$ has the same effect for each of the $J-1$ cumulative logits.\nThe judge effects, which are also independent of $j$, are assumed normal: $u(\\text{judge}_i) \\sim N(0, \\sigma_u^2)$.\nWe are using the logit link because it is the most popular for this kind of model (and the one I am familiar with), but there are other options we will briefly explore later.\n\nThe subtraction of terms in the above model is new to me.\nThe main reason seems to be for familiar interpretation: the larger the value of any independent term $\\beta x$, the smaller the thresholds $\\theta_j$, and therefore a larger probability of the a response falling into a category at the upper end of the scale.\nThis way, $\\beta$ has the same *direction* of effect as in ordinary linear regression.\n\nWe are essentially modeling a \"chain\" of logistic regressions where the binary response is \"less than or equal to a certain level\" vs \"greater than that level\".\nIn this case, with $J$ = 5, the thresholds $\\theta_j$ are capturing the adjusted log-odds of observing:\n\n* $j$ = 1: log-odds of `rating` = 1 vs. 2-5\n* $j$ = 2: log-odds of `rating` = 1-2 vs. 3-5\n* $j$ = 3: log-odds of `rating` = 1-3 vs. 4-5\n* $j$ = 4: log-odds of `rating` = 1-4 vs. 5\n\n### Fitting\n\nNow with a surface-level understanding of what is being modeled, we will fit the data using `ordinal::clm` (cumulative link models) and `ordinal::clmm` (cumulative link mixed models), and logit links.\n\n#### Fixed effects model\n\nFirst, fit a simple model, by maximum likelihood, with `contact` as the sole predictor:\n\n\n$$\n\\text{logit}(p(y_i \\leq j)) = \\theta_j - \\beta_2 \\text{contact}_i\n$$\n\n::: {.cell}\n\n```{.r .cell-code}\nclm_rating_contact <-\n  clm(\n    rating ~ contact,\n    data = wine, link = \"logit\"\n  )\nsummary(clm_rating_contact)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nformula: rating ~ contact\ndata:    wine\n\n link  threshold nobs logLik AIC    niter max.grad cond.H \n logit flexible  72   -99.96 209.91 5(0)  1.67e-07 1.7e+01\n\nCoefficients:\n           Estimate Std. Error z value Pr(>|z|)   \ncontactyes   1.2070     0.4499   2.683   0.0073 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n    Estimate Std. Error z value\n1|2 -2.13933    0.48981  -4.368\n2|3  0.04257    0.32063   0.133\n3|4  1.71449    0.38637   4.437\n4|5  2.97875    0.50207   5.933\n```\n:::\n:::\n\n\nThe model gives us $K - 1 = 4$ threshold coefficients, as expected.\nThe $\\beta_2$ coefficient estimate was statistically significant (by a Wald test), and tells us that `contact` = yes *decreases* the thresholds $\\theta_j$ by $\\beta_2$ = 1.21 (because of the subtraction of model terms), and therefore is associated with *higher* `rating`s.\n\nThe condition number of the Hessian for this model is 16.98.\nThe `ordinal` primer says that larger values (like > `1e4`) might indicate that the model is ill-defined.\n\nIt is nicely illustrative to compare this model to 4 separate logistic regressions with a dichotomized response:\n\n\n$$\n\\begin{align}\n\\text{logit} (p(y_i \\leq 1)) &= \\theta_1 + \\beta_2 \\text{contact}_i \\\\\n\\text{logit} (p(y_i \\leq 2)) &= \\theta_2 + \\beta_2 \\text{contact}_i \\\\\n\\text{logit} (p(y_i \\leq 3)) &= \\theta_3 + \\beta_2 \\text{contact}_i \\\\\n\\text{logit} (p(y_i \\leq 4)) &= \\theta_4 + \\beta_2 \\text{contact}_i\n\\end{align}\n$$\n\n::: {.cell}\n\n```{.r .cell-code}\nwine %>%\n  crossing(j = 1:4) %>%\n  # Create a binary (0 or 1) to indicate where rating <= j\n  mutate(rating_leq_j = as.numeric(rating) <= j) %>%\n  group_by(j) %>%\n  nest() %>%\n  ungroup() %>%\n  mutate(\n    mod = map(\n      data,\n      ~glm(rating_leq_j ~ 1 + contact,\n           data = ., family = binomial(link = \"logit\")) %>% broom::tidy()\n    )\n  ) %>%\n  unnest(mod) %>%\n  transmute(\n    j, term,\n    estimate_se = str_c(round(estimate, 2), \" (\", round(std.error, 2), \")\")\n  ) %>%\n  pivot_wider(names_from = term, values_from = estimate_se) %>%\n  left_join(\n    tidy(clm_rating_contact) %>%\n      transmute(\n        j = as.integer(substr(term, 1, 1)),\n        term = if_else(!is.na(j), \"theta_j\", term),\n        estimate_se = str_c(round(estimate, 2), \" (\", round(std.error, 2), \")\")\n      ) %>%\n      mutate(j = replace_na(j, 1)) %>%\n      spread(term, estimate_se),\n    by = \"j\"\n  ) %>%\n  ungroup() %>%\n  gt() %>%\n  tab_spanner(label = \"Logistic regression\",\n              columns = c(`(Intercept)`, contactyes.x)) %>%\n  tab_spanner(label = \"CLM\",\n              columns = c(theta_j, contactyes.y)) %>%\n  fmt_missing(columns = everything(), missing_text = \"\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ngsetnquxy\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ngsetnquxy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ngsetnquxy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ngsetnquxy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ngsetnquxy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ngsetnquxy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ngsetnquxy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ngsetnquxy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ngsetnquxy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ngsetnquxy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ngsetnquxy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ngsetnquxy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ngsetnquxy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ngsetnquxy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngsetnquxy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ngsetnquxy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ngsetnquxy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngsetnquxy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ngsetnquxy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngsetnquxy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ngsetnquxy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngsetnquxy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ngsetnquxy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngsetnquxy .gt_left {\n  text-align: left;\n}\n\n#ngsetnquxy .gt_center {\n  text-align: center;\n}\n\n#ngsetnquxy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ngsetnquxy .gt_font_normal {\n  font-weight: normal;\n}\n\n#ngsetnquxy .gt_font_bold {\n  font-weight: bold;\n}\n\n#ngsetnquxy .gt_font_italic {\n  font-style: italic;\n}\n\n#ngsetnquxy .gt_super {\n  font-size: 65%;\n}\n\n#ngsetnquxy .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#ngsetnquxy .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ngsetnquxy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ngsetnquxy .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#ngsetnquxy .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#ngsetnquxy .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\">j</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\">\n        <span class=\"gt_column_spanner\">Logistic regression</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\">\n        <span class=\"gt_column_spanner\">CLM</span>\n      </th>\n    </tr>\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">(Intercept)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">contactyes.x</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">theta_j</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">contactyes.y</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_left\">-2.08 (0.53)</td>\n<td class=\"gt_row gt_left\">-1.48 (1.14)</td>\n<td class=\"gt_row gt_left\">-2.14 (0.49)</td>\n<td class=\"gt_row gt_left\">1.21 (0.45)</td></tr>\n    <tr><td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_left\">0 (0.33)</td>\n<td class=\"gt_row gt_left\">-1.1 (0.51)</td>\n<td class=\"gt_row gt_left\">0.04 (0.32)</td>\n<td class=\"gt_row gt_left\"></td></tr>\n    <tr><td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_left\">1.82 (0.48)</td>\n<td class=\"gt_row gt_left\">-1.37 (0.59)</td>\n<td class=\"gt_row gt_left\">1.71 (0.39)</td>\n<td class=\"gt_row gt_left\"></td></tr>\n    <tr><td class=\"gt_row gt_right\">4</td>\n<td class=\"gt_row gt_left\">2.83 (0.73)</td>\n<td class=\"gt_row gt_left\">-1.01 (0.87)</td>\n<td class=\"gt_row gt_left\">2.98 (0.5)</td>\n<td class=\"gt_row gt_left\"></td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nThe intercepts from the ordinary logistic regression correspond closely to the threshold parameters $\\theta_j$ from the cumulative link model.\nIn the fixed effect of `contact` ($\\beta_2$), first note the sign difference, and second notice that the estimate from CLM is about the average of the 4 estimates from logistic regression.\nThe advantage of the CLM is seen in the small standard error in the $\\beta_2$ estimate.\n\nTo quote the primer:\n\n>The cumulative logit model can be seen as the model that combines these four ordinary logistic regression models into a single model and therefore makes better use of the information in the data.\n\nFor the second model, we add the $\\beta_1 \\text{temp}_i$ term:\n\n\n$$\n\\text{logit}(p(y_i \\leq j)) = \\theta_j - \\beta_1 \\text{temp}_i - \\beta_2 \\text{contact}_i\n$$\n\n::: {.cell}\n\n```{.r .cell-code}\nclm_rating_contact_temp <-\n  clm(\n    rating ~ contact + temp,\n    data = wine, link = \"logit\"\n  )\nsummary(clm_rating_contact_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nformula: rating ~ contact + temp\ndata:    wine\n\n link  threshold nobs logLik AIC    niter max.grad cond.H \n logit flexible  72   -86.49 184.98 6(0)  4.01e-12 2.7e+01\n\nCoefficients:\n           Estimate Std. Error z value Pr(>|z|)    \ncontactyes   1.5278     0.4766   3.205  0.00135 ** \ntempwarm     2.5031     0.5287   4.735 2.19e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n    Estimate Std. Error z value\n1|2  -1.3444     0.5171  -2.600\n2|3   1.2508     0.4379   2.857\n3|4   3.4669     0.5978   5.800\n4|5   5.0064     0.7309   6.850\n```\n:::\n:::\n\n\nBoth fixed effects (`contact` = yes and `temp` = warm) are strongly associated with higher probability of higher ratings.\nThe `summary` function provides $p$-values from Wald tests, but more accurate likelihood ratio tests can be done via the `drop1` function, which evaluates each fixed effect while controlling the other:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrop1(clm_rating_contact_temp, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSingle term deletions\n\nModel:\nrating ~ contact + temp\n        Df    AIC    LRT  Pr(>Chi)    \n<none>     184.98                     \ncontact  1 194.03 11.043 0.0008902 ***\ntemp     1 209.91 26.928 2.112e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nOr the reverse via the `add1()` function, which evaluates each fixed effect while ignoring the other:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the null model first\nclm_rating_null <- clm(rating ~ 1, data = wine, link = \"logit\")\nadd1(clm_rating_null, scope = ~ contact + temp, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSingle term additions\n\nModel:\nrating ~ 1\n        Df    AIC     LRT  Pr(>Chi)    \n<none>     215.44                      \ncontact  1 209.91  7.5263   0.00608 ** \ntemp     1 194.03 23.4113 1.308e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nSymmetric Wald confidence intervals can be extracted with `confint` or with `broom::tidy`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(clm_rating_contact_temp, conf.int = TRUE, conf.type = \"Wald\") %>%\n  ggplot(aes(y = term, x = estimate)) +\n  geom_point(size = 2) +\n  geom_linerange(size = 1, aes(xmin = conf.low, xmax = conf.high))\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-in-r-part-1_files/figure-html/unnamed-chunk-13-1.png){width=480}\n:::\n:::\n\n\nIn these types of analyses, we are often interested in the odds ratios.\nFor the two categorical fixed effects, which have two levels each, the odds ratios $y \\leq j$ comparing the two levels are:\n\n\n$$\n\\begin{align}\n\\text{OR} &= \\frac{\\gamma_j (\\text{temp} = \\text{warm})}{\\gamma_j (\\text{temp} = \\text{cold})} = \\frac{\\exp(\\theta_j - \\beta_1 - \\beta_2 \\text{contact})}{\\exp (\\theta_j - 0 - \\beta_2 \\text{contact}}) = \\exp(\\beta_1) \\\\\n\\text{OR} &= \\frac{\\gamma_j (\\text{contact} = \\text{yes})}{\\gamma_j (\\text{contact} = \\text{no})} = \\frac{\\exp(\\theta_j - \\beta_1 \\text{temp} - \\beta_2 )}{\\exp (\\theta_j - \\beta_1 \\text{temp} - 0)}) = \\exp(\\beta_2)\n\\end{align}\n$$\n\n\nwhere we have introduced the shorthand $\\gamma_j = \\text{logit} (p(y \\leq j))$.\nCompute those odds ratios, and their corresponding Wald 95% CIs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(clm_rating_contact_temp, conf.int = T, conf.type = \"Wald\") %>%\n  transmute(\n    term, across(c(estimate, conf.low, conf.high), exp)\n  ) %>%\n  gt() %>%\n  fmt_number(c(estimate, conf.low, conf.high), decimals = 2)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ghsbsukliw\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ghsbsukliw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ghsbsukliw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ghsbsukliw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ghsbsukliw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ghsbsukliw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ghsbsukliw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ghsbsukliw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ghsbsukliw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ghsbsukliw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ghsbsukliw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ghsbsukliw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ghsbsukliw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ghsbsukliw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghsbsukliw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ghsbsukliw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ghsbsukliw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghsbsukliw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ghsbsukliw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghsbsukliw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ghsbsukliw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghsbsukliw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ghsbsukliw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghsbsukliw .gt_left {\n  text-align: left;\n}\n\n#ghsbsukliw .gt_center {\n  text-align: center;\n}\n\n#ghsbsukliw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ghsbsukliw .gt_font_normal {\n  font-weight: normal;\n}\n\n#ghsbsukliw .gt_font_bold {\n  font-weight: bold;\n}\n\n#ghsbsukliw .gt_font_italic {\n  font-style: italic;\n}\n\n#ghsbsukliw .gt_super {\n  font-size: 65%;\n}\n\n#ghsbsukliw .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#ghsbsukliw .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ghsbsukliw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ghsbsukliw .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#ghsbsukliw .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#ghsbsukliw .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">1|2</td>\n<td class=\"gt_row gt_right\">0.26</td>\n<td class=\"gt_row gt_right\">0.09</td>\n<td class=\"gt_row gt_right\">0.72</td></tr>\n    <tr><td class=\"gt_row gt_left\">2|3</td>\n<td class=\"gt_row gt_right\">3.49</td>\n<td class=\"gt_row gt_right\">1.48</td>\n<td class=\"gt_row gt_right\">8.24</td></tr>\n    <tr><td class=\"gt_row gt_left\">3|4</td>\n<td class=\"gt_row gt_right\">32.04</td>\n<td class=\"gt_row gt_right\">9.93</td>\n<td class=\"gt_row gt_right\">103.39</td></tr>\n    <tr><td class=\"gt_row gt_left\">4|5</td>\n<td class=\"gt_row gt_right\">149.37</td>\n<td class=\"gt_row gt_right\">35.65</td>\n<td class=\"gt_row gt_right\">625.75</td></tr>\n    <tr><td class=\"gt_row gt_left\">contactyes</td>\n<td class=\"gt_row gt_right\">4.61</td>\n<td class=\"gt_row gt_right\">1.81</td>\n<td class=\"gt_row gt_right\">11.73</td></tr>\n    <tr><td class=\"gt_row gt_left\">tempwarm</td>\n<td class=\"gt_row gt_right\">12.22</td>\n<td class=\"gt_row gt_right\">4.34</td>\n<td class=\"gt_row gt_right\">34.44</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nOne last thing to check: does the data support an interaction between $\\text{temp}_i$ and $\\text{contact}_i$?\n\n\n$$\n\\text{logit}(p(y_i \\leq j)) = \\theta_j - \\beta_1 \\text{temp}_i - \\beta_2 \\text{contact}_i - \\beta_3 \\text{temp}_i \\text{contact}_i\n$$\n\n::: {.cell}\n\n```{.r .cell-code}\nclm_rating_contact_temp_inter <-\n  clm(\n    rating ~ contact * temp, data = wine, link = \"logit\"\n  )\n\n#drop1(clm_rating_contact_temp_inter, test = \"Chisq\") # this accomplishes the same thing as anova()\nanova(clm_rating_contact_temp, clm_rating_contact_temp_inter)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio tests of cumulative link models:\n \n                              formula:                link: threshold:\nclm_rating_contact_temp       rating ~ contact + temp logit flexible  \nclm_rating_contact_temp_inter rating ~ contact * temp logit flexible  \n\n                              no.par    AIC  logLik LR.stat df Pr(>Chisq)\nclm_rating_contact_temp            6 184.98 -86.492                      \nclm_rating_contact_temp_inter      7 186.83 -86.416  0.1514  1     0.6972\n```\n:::\n:::\n\n\nNo, The interaction term `contact:temp` is not supported by the data.\n\n##### Comparison to linear model\n\nConsider the following linear model which treats `rating` as continuous:\n\n\n$$\ny_i = \\alpha + \\beta_1 \\text{temp}_i + \\beta_2 \\text{contact}_i + \\epsilon_i\n$$\n\n\nwhere $\\epsilon_i \\sim N(0, \\sigma_{\\epsilon}^2)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_rating_contact_temp <- lm(as.numeric(rating) ~ contact + temp, data = wine)\n```\n:::\n\n\n\nTo compare this to a CLM, we must use the probit link:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclm_rating_contact_temp_probit <-\n  clm(\n    rating ~ contact + temp, data = wine, link = \"probit\"\n  )\ntidy(clm_rating_contact_temp_probit) %>%\n  filter(coef.type == \"location\") %>%\n  mutate(model = \"CLM\") %>%\n  select(-coef.type) %>%\n  bind_rows(\n    tidy(lm_rating_contact_temp) %>%\n      filter(term != \"(Intercept)\") %>%\n      # Need to divide by the residual SE here to get the right scale\n      mutate(estimate = estimate / summary(lm_rating_contact_temp)$sigma,\n             model = \"LM\")\n  ) %>%\n  group_by(model) %>%\n  gt() %>%\n  fmt_number(c(estimate, std.error, statistic), decimals = 2) %>%\n  fmt(p.value, fns = scales::pvalue)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"xajmoyprgp\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#xajmoyprgp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xajmoyprgp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xajmoyprgp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xajmoyprgp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xajmoyprgp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xajmoyprgp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xajmoyprgp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xajmoyprgp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xajmoyprgp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xajmoyprgp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xajmoyprgp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xajmoyprgp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xajmoyprgp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xajmoyprgp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xajmoyprgp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xajmoyprgp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xajmoyprgp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xajmoyprgp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xajmoyprgp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xajmoyprgp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xajmoyprgp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xajmoyprgp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xajmoyprgp .gt_left {\n  text-align: left;\n}\n\n#xajmoyprgp .gt_center {\n  text-align: center;\n}\n\n#xajmoyprgp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xajmoyprgp .gt_font_normal {\n  font-weight: normal;\n}\n\n#xajmoyprgp .gt_font_bold {\n  font-weight: bold;\n}\n\n#xajmoyprgp .gt_font_italic {\n  font-style: italic;\n}\n\n#xajmoyprgp .gt_super {\n  font-size: 65%;\n}\n\n#xajmoyprgp .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#xajmoyprgp .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#xajmoyprgp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xajmoyprgp .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#xajmoyprgp .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#xajmoyprgp .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <td colspan=\"5\" class=\"gt_group_heading\">CLM</td>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td class=\"gt_row gt_left\">contactyes</td>\n<td class=\"gt_row gt_right\">0.87</td>\n<td class=\"gt_row gt_right\">0.27</td>\n<td class=\"gt_row gt_right\">3.25</td>\n<td class=\"gt_row gt_right\">0.001</td></tr>\n    <tr><td class=\"gt_row gt_left\">tempwarm</td>\n<td class=\"gt_row gt_right\">1.50</td>\n<td class=\"gt_row gt_right\">0.29</td>\n<td class=\"gt_row gt_right\">5.14</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <td colspan=\"5\" class=\"gt_group_heading\">LM</td>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td class=\"gt_row gt_left\">contactyes</td>\n<td class=\"gt_row gt_right\">0.79</td>\n<td class=\"gt_row gt_right\">0.20</td>\n<td class=\"gt_row gt_right\">3.36</td>\n<td class=\"gt_row gt_right\">0.001</td></tr>\n    <tr><td class=\"gt_row gt_left\">tempwarm</td>\n<td class=\"gt_row gt_right\">1.38</td>\n<td class=\"gt_row gt_right\">0.20</td>\n<td class=\"gt_row gt_right\">5.87</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nThe relative estimates from the linear model are lower than those from the CLM (probit link), indicating that the assumptions of the linear model are not met.\nIn particular, the distance between thresholds is not equidistant, as we can see from differences in the CLM coefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff(coef(clm_rating_contact_temp_probit)[1:4]) %>% round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 2|3  3|4  4|5 \n1.51 1.31 0.90 \n```\n:::\n:::\n\n\n#### Mixed effects model\n\nNow that we have explored ordinal regression with just fixed effects, we will fit the following random effects model:\n\n\n$$\n\\begin{align}\n\\text{logit}(p(y_i \\leq j)) &= \\theta_j - \\beta_1 \\text{temp}_i - \\beta_2 \\text{contact}_i - u( \\text{judge}_i) \\\\\ni &= 1, \\dots n \\; \\; \\; \\; \\; \\; j = 1, \\dots, J - 1\n\\end{align}\n$$\n\n\nwhere the judge effects are independent of $j$, and assumed normal: $u(\\text{judge}_i) \\sim N(0, \\sigma_u^2)$.\n\nEach judge has 8 `rating`s each (two per combination of `temp` and `contact`).\nSee if we can spot the `judge` variance in a plot of `rating`s:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine %>%\n  count(judge, rating) %>%\n  ggplot(aes(x = judge, y = rating)) +\n  geom_tile(aes(fill = n)) +\n  geom_text(aes(label = n), color = \"white\") +\n  scale_x_discrete(expand = c(0, 0)) +\n  scale_y_discrete(expand = c(0, 0)) +\n  theme(legend.position = \"none\") +\n  labs(title = \"Number of ratings by judge\")\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-in-r-part-1_files/figure-html/unnamed-chunk-19-1.png){width=480}\n:::\n:::\n\n\nThere is definitely some judge-specific variability in the perception of bitterness of wine.\n`judge` 5, for instance, doesn't stray far from `rating` = 3, while `judge` 7 didn't consider any of the wines particularly bitter.\n\nFit the full model with `ordinal::clmm` and logit link:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclmm_rating_contact_temp <-\n  clmm(\n    rating ~ temp + contact + (1|judge),\n    data = wine, link = \"logit\"\n  )\n# This is an older function, which we need to run stats::profile later\nclmm2_rating_contact_temp <-\n  clmm2(\n    rating ~ temp + contact, random = judge,\n    data = wine, link = \"logistic\"\n  )\nsummary(clmm_rating_contact_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCumulative Link Mixed Model fitted with the Laplace approximation\n\nformula: rating ~ temp + contact + (1 | judge)\ndata:    wine\n\n link  threshold nobs logLik AIC    niter    max.grad cond.H \n logit flexible  72   -81.57 177.13 332(999) 1.03e-05 2.8e+01\n\nRandom effects:\n Groups Name        Variance Std.Dev.\n judge  (Intercept) 1.279    1.131   \nNumber of groups:  judge 9 \n\nCoefficients:\n           Estimate Std. Error z value Pr(>|z|)    \ntempwarm     3.0630     0.5954   5.145 2.68e-07 ***\ncontactyes   1.8349     0.5125   3.580 0.000344 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n    Estimate Std. Error z value\n1|2  -1.6237     0.6824  -2.379\n2|3   1.5134     0.6038   2.507\n3|4   4.2285     0.8090   5.227\n4|5   6.0888     0.9725   6.261\n```\n:::\n:::\n\n\nCompare model coefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  CLM = tidy(clm_rating_contact_temp),\n  CLMM = tidy(clmm_rating_contact_temp),\n  .id = \"model\"\n) %>%\n  select(-coef.type) %>%\n  group_by(model) %>%\n  gt() %>%\n  fmt_number(c(estimate, std.error, statistic), decimals = 2) %>%\n  fmt(p.value, fns = scales::pvalue)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"isdpgeijpg\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#isdpgeijpg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#isdpgeijpg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#isdpgeijpg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#isdpgeijpg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#isdpgeijpg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#isdpgeijpg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#isdpgeijpg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#isdpgeijpg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#isdpgeijpg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#isdpgeijpg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#isdpgeijpg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#isdpgeijpg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#isdpgeijpg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#isdpgeijpg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#isdpgeijpg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#isdpgeijpg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#isdpgeijpg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#isdpgeijpg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#isdpgeijpg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#isdpgeijpg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#isdpgeijpg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#isdpgeijpg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#isdpgeijpg .gt_left {\n  text-align: left;\n}\n\n#isdpgeijpg .gt_center {\n  text-align: center;\n}\n\n#isdpgeijpg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#isdpgeijpg .gt_font_normal {\n  font-weight: normal;\n}\n\n#isdpgeijpg .gt_font_bold {\n  font-weight: bold;\n}\n\n#isdpgeijpg .gt_font_italic {\n  font-style: italic;\n}\n\n#isdpgeijpg .gt_super {\n  font-size: 65%;\n}\n\n#isdpgeijpg .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#isdpgeijpg .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#isdpgeijpg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#isdpgeijpg .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#isdpgeijpg .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#isdpgeijpg .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <td colspan=\"5\" class=\"gt_group_heading\">CLM</td>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td class=\"gt_row gt_left\">1|2</td>\n<td class=\"gt_row gt_right\">&minus;1.34</td>\n<td class=\"gt_row gt_right\">0.52</td>\n<td class=\"gt_row gt_right\">&minus;2.60</td>\n<td class=\"gt_row gt_right\">0.009</td></tr>\n    <tr><td class=\"gt_row gt_left\">2|3</td>\n<td class=\"gt_row gt_right\">1.25</td>\n<td class=\"gt_row gt_right\">0.44</td>\n<td class=\"gt_row gt_right\">2.86</td>\n<td class=\"gt_row gt_right\">0.004</td></tr>\n    <tr><td class=\"gt_row gt_left\">3|4</td>\n<td class=\"gt_row gt_right\">3.47</td>\n<td class=\"gt_row gt_right\">0.60</td>\n<td class=\"gt_row gt_right\">5.80</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n    <tr><td class=\"gt_row gt_left\">4|5</td>\n<td class=\"gt_row gt_right\">5.01</td>\n<td class=\"gt_row gt_right\">0.73</td>\n<td class=\"gt_row gt_right\">6.85</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n    <tr><td class=\"gt_row gt_left\">contactyes</td>\n<td class=\"gt_row gt_right\">1.53</td>\n<td class=\"gt_row gt_right\">0.48</td>\n<td class=\"gt_row gt_right\">3.21</td>\n<td class=\"gt_row gt_right\">0.001</td></tr>\n    <tr><td class=\"gt_row gt_left\">tempwarm</td>\n<td class=\"gt_row gt_right\">2.50</td>\n<td class=\"gt_row gt_right\">0.53</td>\n<td class=\"gt_row gt_right\">4.73</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <td colspan=\"5\" class=\"gt_group_heading\">CLMM</td>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td class=\"gt_row gt_left\">1|2</td>\n<td class=\"gt_row gt_right\">&minus;1.62</td>\n<td class=\"gt_row gt_right\">0.68</td>\n<td class=\"gt_row gt_right\">&minus;2.38</td>\n<td class=\"gt_row gt_right\">0.017</td></tr>\n    <tr><td class=\"gt_row gt_left\">2|3</td>\n<td class=\"gt_row gt_right\">1.51</td>\n<td class=\"gt_row gt_right\">0.60</td>\n<td class=\"gt_row gt_right\">2.51</td>\n<td class=\"gt_row gt_right\">0.012</td></tr>\n    <tr><td class=\"gt_row gt_left\">3|4</td>\n<td class=\"gt_row gt_right\">4.23</td>\n<td class=\"gt_row gt_right\">0.81</td>\n<td class=\"gt_row gt_right\">5.23</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n    <tr><td class=\"gt_row gt_left\">4|5</td>\n<td class=\"gt_row gt_right\">6.09</td>\n<td class=\"gt_row gt_right\">0.97</td>\n<td class=\"gt_row gt_right\">6.26</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n    <tr><td class=\"gt_row gt_left\">tempwarm</td>\n<td class=\"gt_row gt_right\">3.06</td>\n<td class=\"gt_row gt_right\">0.60</td>\n<td class=\"gt_row gt_right\">5.14</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n    <tr><td class=\"gt_row gt_left\">contactyes</td>\n<td class=\"gt_row gt_right\">1.83</td>\n<td class=\"gt_row gt_right\">0.51</td>\n<td class=\"gt_row gt_right\">3.58</td>\n<td class=\"gt_row gt_right\"><0.001</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nBoth fixed effect estimates $\\beta_1$ and $\\beta_2$ are higher in the CLMM.\nUse `anova` to compare the CLMM to the CLM:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(clm_rating_contact_temp, clmm_rating_contact_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio tests of cumulative link models:\n \n                         formula:                              link: threshold:\nclm_rating_contact_temp  rating ~ contact + temp               logit flexible  \nclmm_rating_contact_temp rating ~ temp + contact + (1 | judge) logit flexible  \n\n                         no.par    AIC  logLik LR.stat df Pr(>Chisq)   \nclm_rating_contact_temp       6 184.98 -86.492                         \nclmm_rating_contact_temp      7 177.13 -81.565   9.853  1   0.001696 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nUnsurprisingly, the `judge` term makes a significant improvement to the fit.\nWe can extract profile confidence intervals on the variance $\\sigma_u$ using `stats::profile`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofile(clmm2_rating_contact_temp,\n        range = c(0.1, 4), nSteps = 30, trace = 0) %>%\n  confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          2.5 %  97.5 %\nstDev 0.5014584 2.26678\n```\n:::\n:::\n\n\nNote that these intervals are asymmetric ($\\sigma_u$ = 1.28), unlike the less accurate Wald tests.\nWe can produce \"best guess\" estimates for `judge` effects using *conditional modes*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  judge_effect = clmm_rating_contact_temp$ranef,\n  cond_var = clmm_rating_contact_temp$condVar\n) %>%\n  mutate(\n    judge = fct_reorder(factor(1:n()), judge_effect),\n    conf.low = judge_effect - qnorm(0.975) * sqrt(cond_var),\n    conf.high = judge_effect + qnorm(0.975) * sqrt(cond_var)\n  ) %>%\n  ggplot(aes(y = judge, x = judge_effect)) +\n  geom_point(size = 2) +\n  geom_linerange(size = 1, aes(xmin = conf.low, xmax = conf.high)) +\n  theme(panel.grid.major.x = element_line(color = \"grey\"))\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-in-r-part-1_files/figure-html/unnamed-chunk-24-1.png){width=384}\n:::\n:::\n\n\n##### Predictions\n\nThere are different ways to extract predicted probabilities.\nFirst, and most obviously, with the `predict` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine %>%\n  bind_cols(\n    pred =  predict(\n      # Have to use clmm2 for predict\n      clmm2_rating_contact_temp, newdata = wine\n    )\n  ) %>%\n  # These are predicted probabilities for the average judge, so we can\n  #  exclude the judge variable\n  distinct(rating, temp, contact, pred) %>%\n  arrange(temp, contact, rating)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 15 × 4\n   rating temp  contact   pred\n   <ord>  <fct> <fct>    <dbl>\n 1 1      cold  no      0.165 \n 2 2      cold  no      0.655 \n 3 3      cold  no      0.166 \n 4 1      cold  yes     0.0305\n 5 2      cold  yes     0.390 \n 6 3      cold  yes     0.496 \n 7 4      cold  yes     0.0696\n 8 2      warm  no      0.166 \n 9 3      warm  no      0.587 \n10 4      warm  no      0.191 \n11 5      warm  no      0.0463\n12 2      warm  yes     0.0313\n13 3      warm  yes     0.306 \n14 4      warm  yes     0.428 \n15 5      warm  yes     0.233 \n```\n:::\n:::\n\n\nThis only gives us predictions for `rating`, `temp` and `contact` values which exist in the data.\nThere is no predicted probability for `rating` > 3, `temp` cold and `contact` no, for example.\n\nAnother way is to pre-specify which values we want to predict:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnd <-\n  crossing(\n    temp = factor(c(\"cold\", \"warm\")),\n    contact = factor(c(\"no\", \"yes\")),\n    rating = factor(1:5, ordered = T)\n  )\nnd %>%\n  bind_cols(pred = predict(clmm2_rating_contact_temp, nd)) %>%\n  ggplot(aes(x = glue::glue(\"{temp}-{contact}\"), y = pred, fill = rating)) +\n  geom_col() +\n  scale_fill_td(palette = \"div5\") +\n  scale_y_continuous(expand = c(0, 0), labels = scales::percent) +\n  labs(x = \"temp-contact\", y = \"predicted probability\")\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-in-r-part-1_files/figure-html/unnamed-chunk-26-1.png){width=480}\n:::\n:::\n\n\n\n\nWe can also get model-estimated cumulative probabilities by considering the model coefficients.\nFor example, for a cold `temp` and `contact`, the cumulative probability of a bitterness `rating` $j$ or less:\n\n\n$$\nP(y_i \\leq j) = \\text{logit}^{-1} [\\theta_j - \\beta_2 \\text{contact}_i]\n$$\n\n\nwhere we are considering the average judge ($u(\\text{judge}_i) = 0$).\nThe inverse logit is $\\text{logit}^{-1}(x) = 1 / (1 + \\exp(-x))$, and can be calculated with `plogis` as a shorthand (`brms::inv_logit_scaled` is another).\nWe can subtract cumulative probabilities to get non-cumulative probabilities of a rating $j$.\nFor example, $j$ = 3:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplogis(clmm_rating_contact_temp$Theta[3] - clmm_rating_contact_temp$beta[2]) -\n  plogis(clmm_rating_contact_temp$Theta[2] - clmm_rating_contact_temp$beta[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncontactyes \n 0.4960357 \n```\n:::\n:::\n\n\nwhich matches the value calculated previously using `predict`.\n\n\n\n\n\n##### Estimated marginal means\n\nThe `emmeans` package provides functionality for estimating marginal mean effects of ordinal models.\nThe package documentation also provides an example using `ordinal` and `wine` data [here](https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html#ordinal).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n:::\n\n\nIn the \"Models supported by `emmeans`\" document, we see the following:\n\n| Object.class | Package | Group | Arguments/notes                                                                                 |   |\n|--------------|---------|-------|-------------------------------------------------------------------------------------------------|---|\n| clm          | ordinal | O     | `mode = c(\"latent\", \"linear.predictor\", \"cum.prob\", \"exc.prob\", \"prob\", \"mean.class\", \"scale\")` |   |\n| clmm         | ordinal | O     | Like `clm` but no `\"scale\"` mode                                                                |   |\n|              |         |       |                                                                                                 |   |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(clmm_rating_contact_temp,\n        specs = list(pairwise ~ temp, pairwise ~ contact), mode = \"latent\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$`emmeans of temp`\n temp emmean    SE  df asymp.LCL asymp.UCL\n cold  -1.63 0.547 Inf    -2.707    -0.562\n warm   1.43 0.532 Inf     0.387     2.470\n\nResults are averaged over the levels of: contact \nConfidence level used: 0.95 \n\n$`pairwise differences of temp`\n 1           estimate    SE  df z.ratio p.value\n cold - warm    -3.06 0.595 Inf  -5.145  <.0001\n\nResults are averaged over the levels of: contact \n\n$`emmeans of contact`\n contact emmean    SE  df asymp.LCL asymp.UCL\n no      -1.020 0.522 Inf    -2.043   0.00274\n yes      0.815 0.513 Inf    -0.191   1.82072\n\nResults are averaged over the levels of: temp \nConfidence level used: 0.95 \n\n$`pairwise differences of contact`\n 1        estimate    SE  df z.ratio p.value\n no - yes    -1.83 0.513 Inf  -3.580  0.0003\n\nResults are averaged over the levels of: temp \n```\n:::\n:::\n\n\nThe contrast estimates are in terms of the latent (underlying unobserved) bitterness `rating`.\n\nUsing `mode = \"cum.prob\"` and `mode = \"exc.prob`\", we can get cumulative probabilities and exceedance (1 - cumulative) probabilities.\nFor example, the probability of a `rating` of at least 4 for different `temp`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(clmm_rating_contact_temp, ~ temp,\n        mode = \"exc.prob\", at = list(cut = \"3|4\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n temp exc.prob     SE  df asymp.LCL asymp.UCL\n cold    0.049 0.0304 Inf   -0.0107     0.109\n warm    0.450 0.1084 Inf    0.2371     0.662\n\nResults are averaged over the levels of: contact \nConfidence level used: 0.95 \n```\n:::\n:::\n\n\n`mode = \"prob\"` gives us probability distributions of each `rating`, which have a nice auto `plot` functionality:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(clmm_rating_contact_temp,\n        ~ rating | temp, mode = \"prob\") %>%\n  plot() +\n  add_facet_borders()\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-in-r-part-1_files/figure-html/unnamed-chunk-33-1.png){width=480}\n:::\n:::\n\n\n\n##### Choice of link function\n\nSo far, we have used the logit link (and briefly the probit link to compare estimates with linear regression).\nThe links available to `ordinal::clmm` are logit, probit, cloglog, loglog, and cauchit.\n\nWe can fit the CLMM using all of these links and compare log-likelihoods:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine %>%\n  nest(data = everything()) %>%\n  crossing(\n    link = c(\"logit\", \"probit\", \"cloglog\", \"loglog\", \"cauchit\")\n  ) %>%\n  mutate(\n    mod = map2(\n      data, link,\n      ~clmm(\n        rating ~ 1 + contact + temp + (1|judge),\n        data = .x, link = .y\n      )\n    )\n  ) %>%\n  mutate(mod_summary = map(mod, glance)) %>%\n  unnest(mod_summary) %>%\n  select(link, logLik, AIC, BIC) %>%\n  arrange(logLik) %>%\n  gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"eebigysxcd\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#eebigysxcd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#eebigysxcd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#eebigysxcd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#eebigysxcd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#eebigysxcd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#eebigysxcd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#eebigysxcd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#eebigysxcd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#eebigysxcd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#eebigysxcd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#eebigysxcd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#eebigysxcd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#eebigysxcd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eebigysxcd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#eebigysxcd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#eebigysxcd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eebigysxcd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#eebigysxcd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eebigysxcd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#eebigysxcd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eebigysxcd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eebigysxcd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eebigysxcd .gt_left {\n  text-align: left;\n}\n\n#eebigysxcd .gt_center {\n  text-align: center;\n}\n\n#eebigysxcd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#eebigysxcd .gt_font_normal {\n  font-weight: normal;\n}\n\n#eebigysxcd .gt_font_bold {\n  font-weight: bold;\n}\n\n#eebigysxcd .gt_font_italic {\n  font-style: italic;\n}\n\n#eebigysxcd .gt_super {\n  font-size: 65%;\n}\n\n#eebigysxcd .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#eebigysxcd .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#eebigysxcd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#eebigysxcd .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#eebigysxcd .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#eebigysxcd .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">link</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\">logLik</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">AIC</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">BIC</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">cauchit</td>\n<td class=\"gt_row gt_center\">-86.83499</td>\n<td class=\"gt_row gt_right\">187.6700</td>\n<td class=\"gt_row gt_right\">203.6066</td></tr>\n    <tr><td class=\"gt_row gt_left\">cloglog</td>\n<td class=\"gt_row gt_center\">-82.72936</td>\n<td class=\"gt_row gt_right\">179.4587</td>\n<td class=\"gt_row gt_right\">195.3954</td></tr>\n    <tr><td class=\"gt_row gt_left\">logit</td>\n<td class=\"gt_row gt_center\">-81.56541</td>\n<td class=\"gt_row gt_right\">177.1308</td>\n<td class=\"gt_row gt_right\">193.0675</td></tr>\n    <tr><td class=\"gt_row gt_left\">loglog</td>\n<td class=\"gt_row gt_center\">-81.54137</td>\n<td class=\"gt_row gt_right\">177.0827</td>\n<td class=\"gt_row gt_right\">193.0194</td></tr>\n    <tr><td class=\"gt_row gt_left\">probit</td>\n<td class=\"gt_row gt_center\">-80.93061</td>\n<td class=\"gt_row gt_right\">175.8612</td>\n<td class=\"gt_row gt_right\">191.7979</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nThe probit model appears to be the best description of the data.\n\nWe can also consider the effect of \"flexible\" vs \"equidistant\" thresholds:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine %>%\n  nest(data = everything()) %>%\n  crossing(\n    link = c(\"logit\", \"probit\", \"cloglog\", \"loglog\", \"cauchit\"),\n    threshold = c(\"flexible\", \"equidistant\")\n  ) %>%\n  mutate(\n    mod = pmap(\n      list(data, link, threshold),\n      function(a, b, c) {\n        clmm(\n          rating ~ 1 + contact + temp + (1|judge),\n          data = a, link = b, threshold = c\n        )\n      }\n    )\n  ) %>%\n  #mutate(mod_summary = map(mod, glance)) %>%\n  mutate(\n    mod_summary = map(\n      mod,\n      # glance() on a clmm object returns a <logLik> variable type which\n      #  can't be bound together by unnest(), so need to convert it to numeric\n      ~glance(.x) %>% mutate(logLik = as.numeric(logLik))\n    )\n  ) %>%\n  unnest(mod_summary) %>%\n  select(link, threshold, logLik, edf, AIC, BIC) %>%\n  arrange(logLik) %>%\n  gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"pxettaknss\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#pxettaknss .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pxettaknss .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pxettaknss .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pxettaknss .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pxettaknss .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxettaknss .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pxettaknss .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pxettaknss .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pxettaknss .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pxettaknss .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pxettaknss .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pxettaknss .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pxettaknss .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pxettaknss .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pxettaknss .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pxettaknss .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pxettaknss .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxettaknss .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pxettaknss .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pxettaknss .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxettaknss .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pxettaknss .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pxettaknss .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxettaknss .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxettaknss .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pxettaknss .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pxettaknss .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxettaknss .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pxettaknss .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxettaknss .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pxettaknss .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxettaknss .gt_left {\n  text-align: left;\n}\n\n#pxettaknss .gt_center {\n  text-align: center;\n}\n\n#pxettaknss .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pxettaknss .gt_font_normal {\n  font-weight: normal;\n}\n\n#pxettaknss .gt_font_bold {\n  font-weight: bold;\n}\n\n#pxettaknss .gt_font_italic {\n  font-style: italic;\n}\n\n#pxettaknss .gt_super {\n  font-size: 65%;\n}\n\n#pxettaknss .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#pxettaknss .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#pxettaknss .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pxettaknss .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#pxettaknss .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#pxettaknss .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">link</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">threshold</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">logLik</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">edf</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">AIC</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">BIC</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">cauchit</td>\n<td class=\"gt_row gt_left\">equidistant</td>\n<td class=\"gt_row gt_right\">-87.75021</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">185.5004</td>\n<td class=\"gt_row gt_right\">196.8837</td></tr>\n    <tr><td class=\"gt_row gt_left\">cauchit</td>\n<td class=\"gt_row gt_left\">flexible</td>\n<td class=\"gt_row gt_right\">-86.83499</td>\n<td class=\"gt_row gt_right\">7</td>\n<td class=\"gt_row gt_right\">187.6700</td>\n<td class=\"gt_row gt_right\">203.6066</td></tr>\n    <tr><td class=\"gt_row gt_left\">loglog</td>\n<td class=\"gt_row gt_left\">equidistant</td>\n<td class=\"gt_row gt_right\">-84.36440</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">178.7288</td>\n<td class=\"gt_row gt_right\">190.1121</td></tr>\n    <tr><td class=\"gt_row gt_left\">cloglog</td>\n<td class=\"gt_row gt_left\">equidistant</td>\n<td class=\"gt_row gt_right\">-83.32634</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">176.6527</td>\n<td class=\"gt_row gt_right\">188.0360</td></tr>\n    <tr><td class=\"gt_row gt_left\">logit</td>\n<td class=\"gt_row gt_left\">equidistant</td>\n<td class=\"gt_row gt_right\">-83.05497</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">176.1099</td>\n<td class=\"gt_row gt_right\">187.4933</td></tr>\n    <tr><td class=\"gt_row gt_left\">cloglog</td>\n<td class=\"gt_row gt_left\">flexible</td>\n<td class=\"gt_row gt_right\">-82.72936</td>\n<td class=\"gt_row gt_right\">7</td>\n<td class=\"gt_row gt_right\">179.4587</td>\n<td class=\"gt_row gt_right\">195.3954</td></tr>\n    <tr><td class=\"gt_row gt_left\">probit</td>\n<td class=\"gt_row gt_left\">equidistant</td>\n<td class=\"gt_row gt_right\">-82.52622</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">175.0524</td>\n<td class=\"gt_row gt_right\">186.4358</td></tr>\n    <tr><td class=\"gt_row gt_left\">logit</td>\n<td class=\"gt_row gt_left\">flexible</td>\n<td class=\"gt_row gt_right\">-81.56541</td>\n<td class=\"gt_row gt_right\">7</td>\n<td class=\"gt_row gt_right\">177.1308</td>\n<td class=\"gt_row gt_right\">193.0675</td></tr>\n    <tr><td class=\"gt_row gt_left\">loglog</td>\n<td class=\"gt_row gt_left\">flexible</td>\n<td class=\"gt_row gt_right\">-81.54137</td>\n<td class=\"gt_row gt_right\">7</td>\n<td class=\"gt_row gt_right\">177.0827</td>\n<td class=\"gt_row gt_right\">193.0194</td></tr>\n    <tr><td class=\"gt_row gt_left\">probit</td>\n<td class=\"gt_row gt_left\">flexible</td>\n<td class=\"gt_row gt_right\">-80.93061</td>\n<td class=\"gt_row gt_right\">7</td>\n<td class=\"gt_row gt_right\">175.8612</td>\n<td class=\"gt_row gt_right\">191.7979</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nNote the change in degrees of freedom, resulting in the equidistant probit model having the lowest BIC.\nIn terms of log likelihood, however, flexible always outperform equidistant thresholds.\n\n## Conclusion\n\nThanks to detailed documentation, fitting cumulative link (mixed) models is very easy with `ordinal`.\nIn this post, we first learned the theoretical basis for these models, then worked through examples using `wine` bitterness ratings from multiple judges.\n\nIn the next post, I'll explore the Bayesian approach to ordinal regression with the `brms` package.\n\n## Reproducibility {.appendix}\n\n<details><summary>Session info</summary>\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n setting  value\n version  R version 4.2.1 (2022-06-23 ucrt)\n os       Windows 10 x64 (build 19044)\n system   x86_64, mingw32\n ui       RTerm\n language (EN)\n collate  English_Canada.utf8\n ctype    English_Canada.utf8\n tz       America/Curacao\n date     2022-08-07\n pandoc   2.18 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)\n```\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"package\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"ondiskversion\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"loadedversion\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"path\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"loadedpath\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"attached\"],\"name\":[6],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"is_base\"],\"name\":[7],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"date\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"source\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"md5ok\"],\"name\":[10],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"library\"],\"name\":[11],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"assertthat\",\"2\":\"0.2.1\",\"3\":\"0.2.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/assertthat\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/assertthat\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-03-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"assertthat\"},{\"1\":\"backports\",\"2\":\"1.4.1\",\"3\":\"1.4.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/backports\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/backports\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-13\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"backports\"},{\"1\":\"broom\",\"2\":\"1.0.0\",\"3\":\"1.0.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/broom\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/broom\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-07-01\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"broom\"},{\"1\":\"cachem\",\"2\":\"1.0.6\",\"3\":\"1.0.6\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cachem\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cachem\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-19\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"cachem\"},{\"1\":\"callr\",\"2\":\"3.7.1\",\"3\":\"3.7.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/callr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/callr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-13\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"callr\"},{\"1\":\"cellranger\",\"2\":\"1.1.0\",\"3\":\"1.1.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cellranger\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cellranger\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2016-07-27\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"cellranger\"},{\"1\":\"checkmate\",\"2\":\"2.1.0\",\"3\":\"2.1.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/checkmate\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/checkmate\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"checkmate\"},{\"1\":\"cli\",\"2\":\"3.3.0\",\"3\":\"3.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cli\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/cli\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"cli\"},{\"1\":\"coda\",\"2\":\"0.19.4\",\"3\":\"0.19-4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/coda\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/coda\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-09-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"coda\"},{\"1\":\"colorspace\",\"2\":\"2.0.3\",\"3\":\"2.0-3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/colorspace\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/colorspace\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"colorspace\"},{\"1\":\"crayon\",\"2\":\"1.5.1\",\"3\":\"1.5.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/crayon\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/crayon\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"crayon\"},{\"1\":\"DBI\",\"2\":\"1.1.3\",\"3\":\"1.1.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/DBI\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/DBI\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-06-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"DBI\"},{\"1\":\"dbplyr\",\"2\":\"2.2.1\",\"3\":\"2.2.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dbplyr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dbplyr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-06-27\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"dbplyr\"},{\"1\":\"devtools\",\"2\":\"2.4.4\",\"3\":\"2.4.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/devtools\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/devtools\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-20\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"devtools\"},{\"1\":\"digest\",\"2\":\"0.6.29\",\"3\":\"0.6.29\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/digest\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/digest\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-01\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"digest\"},{\"1\":\"distill\",\"2\":\"1.4\",\"3\":\"1.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/distill\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/distill\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-05-12\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"distill\"},{\"1\":\"downlit\",\"2\":\"0.4.2\",\"3\":\"0.4.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/downlit\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/downlit\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"downlit\"},{\"1\":\"dplyr\",\"2\":\"1.0.9\",\"3\":\"1.0.9\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dplyr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dplyr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-04-28\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"dplyr\"},{\"1\":\"dunnr\",\"2\":\"0.2.6\",\"3\":\"0.2.6\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dunnr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/dunnr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-08-07\",\"9\":\"Github (taylordunn/dunnr@e2a82136012b9edae43fc5f8e728492125366267)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"dunnr\"},{\"1\":\"ellipsis\",\"2\":\"0.3.2\",\"3\":\"0.3.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ellipsis\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ellipsis\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-04-29\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ellipsis\"},{\"1\":\"emmeans\",\"2\":\"1.8.0\",\"3\":\"1.8.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/emmeans\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/emmeans\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-08-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"emmeans\"},{\"1\":\"estimability\",\"2\":\"1.4.1\",\"3\":\"1.4.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/estimability\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/estimability\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-08-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"estimability\"},{\"1\":\"evaluate\",\"2\":\"0.15\",\"3\":\"0.15\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/evaluate\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/evaluate\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"evaluate\"},{\"1\":\"extrafont\",\"2\":\"0.18\",\"3\":\"0.18\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/extrafont\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/extrafont\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-12\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"extrafont\"},{\"1\":\"extrafontdb\",\"2\":\"1.0\",\"3\":\"1.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/extrafontdb\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/extrafontdb\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2012-06-11\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"extrafontdb\"},{\"1\":\"fansi\",\"2\":\"1.0.3\",\"3\":\"1.0.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fansi\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fansi\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"fansi\"},{\"1\":\"farver\",\"2\":\"2.1.1\",\"3\":\"2.1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/farver\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/farver\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-06\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"farver\"},{\"1\":\"fastmap\",\"2\":\"1.1.0\",\"3\":\"1.1.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fastmap\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fastmap\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-01-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"fastmap\"},{\"1\":\"forcats\",\"2\":\"0.5.1\",\"3\":\"0.5.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/forcats\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/forcats\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2021-01-27\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"forcats\"},{\"1\":\"fs\",\"2\":\"1.5.2\",\"3\":\"1.5.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fs\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/fs\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-08\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"fs\"},{\"1\":\"gargle\",\"2\":\"1.2.0\",\"3\":\"1.2.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gargle\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gargle\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-07-02\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"gargle\"},{\"1\":\"generics\",\"2\":\"0.1.3\",\"3\":\"0.1.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/generics\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/generics\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"generics\"},{\"1\":\"ggplot2\",\"2\":\"3.3.6\",\"3\":\"3.3.6\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ggplot2\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ggplot2\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-05-03\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ggplot2\"},{\"1\":\"ggrepel\",\"2\":\"0.9.1\",\"3\":\"0.9.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ggrepel\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ggrepel\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-01-15\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ggrepel\"},{\"1\":\"glue\",\"2\":\"1.6.2\",\"3\":\"1.6.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/glue\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/glue\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"glue\"},{\"1\":\"googledrive\",\"2\":\"2.0.0\",\"3\":\"2.0.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/googledrive\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/googledrive\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-07-08\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"googledrive\"},{\"1\":\"googlesheets4\",\"2\":\"1.0.0\",\"3\":\"1.0.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/googlesheets4\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/googlesheets4\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-07-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"googlesheets4\"},{\"1\":\"gt\",\"2\":\"0.6.0\",\"3\":\"0.6.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gt\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gt\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-05-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"gt\"},{\"1\":\"gtable\",\"2\":\"0.3.0\",\"3\":\"0.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gtable\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/gtable\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-03-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"gtable\"},{\"1\":\"haven\",\"2\":\"2.5.0\",\"3\":\"2.5.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/haven\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/haven\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-15\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"haven\"},{\"1\":\"hms\",\"2\":\"1.1.1\",\"3\":\"1.1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/hms\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/hms\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"hms\"},{\"1\":\"htmltools\",\"2\":\"0.5.3\",\"3\":\"0.5.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/htmltools\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/htmltools\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"htmltools\"},{\"1\":\"htmlwidgets\",\"2\":\"1.5.4\",\"3\":\"1.5.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/htmlwidgets\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/htmlwidgets\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-08\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"htmlwidgets\"},{\"1\":\"httpuv\",\"2\":\"1.6.5\",\"3\":\"1.6.5\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/httpuv\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/httpuv\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-01-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"httpuv\"},{\"1\":\"httr\",\"2\":\"1.4.3\",\"3\":\"1.4.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/httr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/httr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-05-04\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"httr\"},{\"1\":\"jsonlite\",\"2\":\"1.8.0\",\"3\":\"1.8.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/jsonlite\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/jsonlite\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"jsonlite\"},{\"1\":\"knitr\",\"2\":\"1.39\",\"3\":\"1.39\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/knitr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/knitr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"knitr\"},{\"1\":\"labeling\",\"2\":\"0.4.2\",\"3\":\"0.4.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/labeling\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/labeling\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-10-20\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"labeling\"},{\"1\":\"later\",\"2\":\"1.3.0\",\"3\":\"1.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/later\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/later\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"later\"},{\"1\":\"lattice\",\"2\":\"0.20.45\",\"3\":\"0.20-45\",\"4\":\"C:/Program Files/R/R-4.2.1/library/lattice\",\"5\":\"C:/Program Files/R/R-4.2.1/library/lattice\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"NA\",\"11\":\"C:/Program Files/R/R-4.2.1/library\",\"_rn_\":\"lattice\"},{\"1\":\"lifecycle\",\"2\":\"1.0.1\",\"3\":\"1.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/lifecycle\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/lifecycle\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"lifecycle\"},{\"1\":\"lubridate\",\"2\":\"1.8.0\",\"3\":\"1.8.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/lubridate\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/lubridate\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-10-07\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"lubridate\"},{\"1\":\"magrittr\",\"2\":\"2.0.3\",\"3\":\"2.0.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/magrittr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/magrittr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"magrittr\"},{\"1\":\"MASS\",\"2\":\"7.3.57\",\"3\":\"7.3-57\",\"4\":\"C:/Program Files/R/R-4.2.1/library/MASS\",\"5\":\"C:/Program Files/R/R-4.2.1/library/MASS\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"NA\",\"11\":\"C:/Program Files/R/R-4.2.1/library\",\"_rn_\":\"MASS\"},{\"1\":\"Matrix\",\"2\":\"1.4.1\",\"3\":\"1.4-1\",\"4\":\"C:/Program Files/R/R-4.2.1/library/Matrix\",\"5\":\"C:/Program Files/R/R-4.2.1/library/Matrix\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-23\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"NA\",\"11\":\"C:/Program Files/R/R-4.2.1/library\",\"_rn_\":\"Matrix\"},{\"1\":\"memoise\",\"2\":\"2.0.1\",\"3\":\"2.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/memoise\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/memoise\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"memoise\"},{\"1\":\"mime\",\"2\":\"0.12\",\"3\":\"0.12\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/mime\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/mime\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-09-28\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"mime\"},{\"1\":\"miniUI\",\"2\":\"0.1.1.1\",\"3\":\"0.1.1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/miniUI\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/miniUI\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2018-05-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"miniUI\"},{\"1\":\"modelr\",\"2\":\"0.1.8\",\"3\":\"0.1.8\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/modelr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/modelr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-05-19\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"modelr\"},{\"1\":\"munsell\",\"2\":\"0.5.0\",\"3\":\"0.5.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/munsell\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/munsell\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2018-06-12\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"munsell\"},{\"1\":\"mvtnorm\",\"2\":\"1.1.3\",\"3\":\"1.1-3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/mvtnorm\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/mvtnorm\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-10-08\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"mvtnorm\"},{\"1\":\"numDeriv\",\"2\":\"2016.8.1.1\",\"3\":\"2016.8-1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/numDeriv\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/numDeriv\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-06-06\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"numDeriv\"},{\"1\":\"ordinal\",\"2\":\"2019.12.10\",\"3\":\"2019.12-10\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ordinal\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ordinal\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2019-12-15\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ordinal\"},{\"1\":\"patchwork\",\"2\":\"1.1.1\",\"3\":\"1.1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/patchwork\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/patchwork\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2020-12-17\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"patchwork\"},{\"1\":\"pillar\",\"2\":\"1.8.0\",\"3\":\"1.8.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pillar\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pillar\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"pillar\"},{\"1\":\"pkgbuild\",\"2\":\"1.3.1\",\"3\":\"1.3.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgbuild\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgbuild\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-20\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"pkgbuild\"},{\"1\":\"pkgconfig\",\"2\":\"2.0.3\",\"3\":\"2.0.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgconfig\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgconfig\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-09-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"pkgconfig\"},{\"1\":\"pkgload\",\"2\":\"1.3.0\",\"3\":\"1.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgload\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/pkgload\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-06-27\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"pkgload\"},{\"1\":\"prettyunits\",\"2\":\"1.1.1\",\"3\":\"1.1.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/prettyunits\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/prettyunits\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-01-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"prettyunits\"},{\"1\":\"processx\",\"2\":\"3.7.0\",\"3\":\"3.7.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/processx\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/processx\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-07\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"processx\"},{\"1\":\"profvis\",\"2\":\"0.3.7\",\"3\":\"0.3.7\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/profvis\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/profvis\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-11-02\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"profvis\"},{\"1\":\"promises\",\"2\":\"1.2.0.1\",\"3\":\"1.2.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/promises\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/promises\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-02-11\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"promises\"},{\"1\":\"ps\",\"2\":\"1.7.1\",\"3\":\"1.7.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ps\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ps\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-06-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ps\"},{\"1\":\"purrr\",\"2\":\"0.3.4\",\"3\":\"0.3.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/purrr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/purrr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2020-04-17\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"purrr\"},{\"1\":\"R6\",\"2\":\"2.5.1\",\"3\":\"2.5.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/R6\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/R6\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-19\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"R6\"},{\"1\":\"ragg\",\"2\":\"1.2.2\",\"3\":\"1.2.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ragg\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ragg\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ragg\"},{\"1\":\"Rcpp\",\"2\":\"1.0.9\",\"3\":\"1.0.9\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/Rcpp\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/Rcpp\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-08\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"Rcpp\"},{\"1\":\"readr\",\"2\":\"2.1.2\",\"3\":\"2.1.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/readr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/readr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-01-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"readr\"},{\"1\":\"readxl\",\"2\":\"1.4.0\",\"3\":\"1.4.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/readxl\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/readxl\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-28\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"readxl\"},{\"1\":\"remotes\",\"2\":\"2.4.2\",\"3\":\"2.4.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/remotes\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/remotes\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"remotes\"},{\"1\":\"renv\",\"2\":\"0.15.5\",\"3\":\"0.15.5\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/renv\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/renv\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-05-26\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"renv\"},{\"1\":\"reprex\",\"2\":\"2.0.1\",\"3\":\"2.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/reprex\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/reprex\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-08-05\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"reprex\"},{\"1\":\"rlang\",\"2\":\"1.0.4\",\"3\":\"1.0.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rlang\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rlang\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-12\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rlang\"},{\"1\":\"rmarkdown\",\"2\":\"2.14\",\"3\":\"2.14\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rmarkdown\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rmarkdown\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rmarkdown\"},{\"1\":\"rstudioapi\",\"2\":\"0.13\",\"3\":\"0.13\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rstudioapi\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rstudioapi\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-11-12\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rstudioapi\"},{\"1\":\"Rttf2pt1\",\"2\":\"1.3.8\",\"3\":\"1.3.8\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/Rttf2pt1\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/Rttf2pt1\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2020-01-10\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"Rttf2pt1\"},{\"1\":\"rvest\",\"2\":\"1.0.2\",\"3\":\"1.0.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rvest\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/rvest\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-10-16\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"rvest\"},{\"1\":\"sass\",\"2\":\"0.4.2\",\"3\":\"0.4.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/sass\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/sass\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-16\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"sass\"},{\"1\":\"scales\",\"2\":\"1.2.0\",\"3\":\"1.2.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/scales\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/scales\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-13\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"scales\"},{\"1\":\"sessioninfo\",\"2\":\"1.2.2\",\"3\":\"1.2.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/sessioninfo\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/sessioninfo\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-12-06\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"sessioninfo\"},{\"1\":\"shiny\",\"2\":\"1.7.2\",\"3\":\"1.7.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/shiny\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/shiny\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-19\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"shiny\"},{\"1\":\"stringi\",\"2\":\"1.7.8\",\"3\":\"1.7.8\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/stringi\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/stringi\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-07-11\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"stringi\"},{\"1\":\"stringr\",\"2\":\"1.4.0\",\"3\":\"1.4.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/stringr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/stringr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2019-02-10\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"stringr\"},{\"1\":\"systemfonts\",\"2\":\"1.0.4\",\"3\":\"1.0.4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/systemfonts\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/systemfonts\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-11\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"systemfonts\"},{\"1\":\"textshaping\",\"2\":\"0.3.6\",\"3\":\"0.3.6\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/textshaping\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/textshaping\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-10-13\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"textshaping\"},{\"1\":\"tibble\",\"2\":\"3.1.8\",\"3\":\"3.1.8\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tibble\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tibble\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-07-22\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tibble\"},{\"1\":\"tidyr\",\"2\":\"1.2.0\",\"3\":\"1.2.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyr\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-02-01\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tidyr\"},{\"1\":\"tidyselect\",\"2\":\"1.1.2\",\"3\":\"1.1.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyselect\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyselect\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tidyselect\"},{\"1\":\"tidyverse\",\"2\":\"1.3.2\",\"3\":\"1.3.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyverse\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tidyverse\",\"6\":\"TRUE\",\"7\":\"FALSE\",\"8\":\"2022-07-18\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tidyverse\"},{\"1\":\"tzdb\",\"2\":\"0.3.0\",\"3\":\"0.3.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tzdb\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/tzdb\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-28\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"tzdb\"},{\"1\":\"ucminf\",\"2\":\"1.1.4\",\"3\":\"1.1-4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ucminf\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/ucminf\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2016-08-18\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"ucminf\"},{\"1\":\"urlchecker\",\"2\":\"1.0.1\",\"3\":\"1.0.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/urlchecker\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/urlchecker\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"urlchecker\"},{\"1\":\"usethis\",\"2\":\"2.1.6\",\"3\":\"2.1.6\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/usethis\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/usethis\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-05-25\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"usethis\"},{\"1\":\"utf8\",\"2\":\"1.2.2\",\"3\":\"1.2.2\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/utf8\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/utf8\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-07-24\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"utf8\"},{\"1\":\"vctrs\",\"2\":\"0.4.1\",\"3\":\"0.4.1\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/vctrs\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/vctrs\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-04-13\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"vctrs\"},{\"1\":\"withr\",\"2\":\"2.5.0\",\"3\":\"2.5.0\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/withr\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/withr\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-03-03\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"withr\"},{\"1\":\"xfun\",\"2\":\"0.31\",\"3\":\"0.31\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xfun\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xfun\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-05-10\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"xfun\"},{\"1\":\"xml2\",\"2\":\"1.3.3\",\"3\":\"1.3.3\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xml2\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xml2\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2021-11-30\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"xml2\"},{\"1\":\"xtable\",\"2\":\"1.8.4\",\"3\":\"1.8-4\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xtable\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/xtable\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2019-04-21\",\"9\":\"CRAN (R 4.2.1)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"xtable\"},{\"1\":\"yaml\",\"2\":\"2.3.5\",\"3\":\"2.3.5\",\"4\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/yaml\",\"5\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2/yaml\",\"6\":\"FALSE\",\"7\":\"FALSE\",\"8\":\"2022-02-21\",\"9\":\"CRAN (R 4.2.0)\",\"10\":\"TRUE\",\"11\":\"C:/Users/tdunn/AppData/Local/R/win-library/4.2\",\"_rn_\":\"yaml\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n</details>\n\n<details><summary>Git repository</summary>\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\nLocal:    main C:/Users/tdunn/Documents/tdunn-quarto\nRemote:   main @ origin (https://github.com/taylordunn/tdunn-quarto.git)\nHead:     [53358c7] 2022-08-06: Set fonts and trying out `renv.lock` for reproducibility\n```\n:::\n:::\n\n\n</details>\n\n\n::: {.cell}\n\n:::\n\n<a href=\"https://github.com/taylordunn/tdunn-quarto/tree/main/posts/2020-03-15-ordinal-regression-in-r-part-1\">Source code</a>, <a href=\"https://github.com/taylordunn/tdunn-quarto/tree/main/posts/2020-03-15-ordinal-regression-in-r-part-1/renv.lock\">R environment</a>\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n",
    "supporting": [
      "ordinal-regression-in-r-part-1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}